"""Localization dictionary for bilingual support (Vietnamese & English)."""

LOC = {
    "Tiáº¿ng Viá»‡t": {
        # Navigation
        "nav_play": "ChÆ¡i Ä‘á»‘",
        "nav_run": "Cháº¡y thuáº­t toÃ¡n",
        "nav_trace": "Trace tá»«ng bÆ°á»›c",
        "nav_hand_trace": "Luyá»‡n cháº¡y tay",
        "nav_compare": "So sÃ¡nh",
        "nav_theory": "LÃ½ thuyáº¿t PEAS",
        "nav_advanced": "NÃ¢ng cao (CSP/Äá»‘i khÃ¡ng)",
        "demo_workflow": "Luá»“ng demo",
        "teaching_preset": "TÃ¬nh huá»‘ng dáº¡y há»c",
        "teaching_preset_help": "CÃ¡c ca Ä‘Ã£ kiá»ƒm thá»­ giÃºp nhÃ¬n rÃµ trade-off giá»¯a thuáº­t toÃ¡n.",
        "load_teaching_preset": "Táº£i tÃ¬nh huá»‘ng dáº¡y há»c",
        "play_hero_title": "PhÃ²ng thÃ­ nghiá»‡m giáº£i 15-Puzzle báº±ng AI",
        "play_hero_desc": "Dashboard cuá»‘i ká»³ Ä‘á»ƒ trÃ¬nh bÃ y PEAS, tÃ¬m kiáº¿m khÃ´ng gian tráº¡ng thÃ¡i, heuristic vÃ  ranh giá»›i giá»¯a solver tháº­t vá»›i pháº§n má»Ÿ rá»™ng giÃ¡o dá»¥c.",
        "play_hero_kicker": "Dashboard cuá»‘i ká»³ AI",
        "exam_step_label": "BÆ°á»›c",
        "exam_tab_play": "ChÆ¡i Ä‘á»‘",
        "exam_tab_run": "Cháº¡y thuáº­t toÃ¡n",
        "exam_tab_compare": "So sÃ¡nh",
        "exam_tab_theory": "LÃ½ thuyáº¿t PEAS",
        "exam_tab_hand": "Luyá»‡n cháº¡y tay",
        "exam_step_play_title": "Thiáº¿t láº­p tráº¡ng thÃ¡i",
        "exam_step_play_note": "Táº£i preset hoáº·c kiá»ƒm tra tÃ­nh giáº£i Ä‘Æ°á»£c.",
        "exam_step_run_title": "Trace má»™t solver",
        "exam_step_run_note": "Giáº£i thÃ­ch frontier, reached vÃ  báº£o Ä‘áº£m thuáº­t toÃ¡n.",
        "exam_step_compare_title": "Äo trade-off",
        "exam_step_compare_note": "DÃ¹ng seed, Ä‘á»™ sÃ¢u, heuristic vÃ  caveat.",
        "exam_step_theory_title": "Báº£o vá»‡ mÃ´ hÃ¬nh",
        "exam_step_theory_note": "TrÃ¬nh bÃ y PEAS, chá»©ng minh, taxonomy vÃ  giá»›i háº¡n.",
        "exam_step_hand_title": "Kiá»ƒm chá»©ng báº±ng tay",
        "exam_step_hand_note": "Luyá»‡n thá»© tá»± má»Ÿ rá»™ng vÃ  quy táº¯c phÃ¡ hÃ²a.",
        "run_hero_title": "Cháº¡y má»™t thuáº­t toÃ¡n kÃ¨m ngá»¯ cáº£nh há»c thuáº­t",
        "run_hero_desc": "Kiá»ƒm tra guarantee, giáº£ Ä‘á»‹nh mÃ´i trÆ°á»ng, trace vÃ  lÃ½ do phÆ°Æ¡ng phÃ¡p Ä‘Æ°á»£c chá»n cÃ³ pháº£i solver tá»± nhiÃªn cá»§a 15-puzzle hay khÃ´ng.",
        "run_hero_kicker": "PhÃ¢n tÃ­ch má»™t thuáº­t toÃ¡n",
        "run_model_success_no_goal": "{algo} táº¡o ra káº¿t quáº£ há»£p lá»‡ cho mÃ´ hÃ¬nh demo, nhÆ°ng chÆ°a chá»©ng nháº­n Ä‘Æ°á»ng Ä‘i chuáº©n tá»›i goal yÃªu cáº§u.",
        "run_fresh_seed": "Táº¡o seed ngáº«u nhiÃªn má»›i má»—i láº§n cháº¡y",
        "run_fresh_seed_help": "Báº­t: má»—i láº§n cháº¡y sinh trajectory stochastic má»›i. Táº¯t: dÃ¹ng seed cá»‘ Ä‘á»‹nh Ä‘á»ƒ so sÃ¡nh há»c thuáº­t cÃ³ thá»ƒ tÃ¡i láº­p.",
        "run_fixed_seed": "Seed ngáº«u nhiÃªn cá»‘ Ä‘á»‹nh",
        "run_deterministic_caption": "Láº§n cháº¡y deterministic: cÃ¹ng tráº¡ng thÃ¡i, tham sá»‘, thá»© tá»± hÃ nh Ä‘á»™ng vÃ  tie-breaker cÃ³ thá»ƒ táº¡o cÃ¹ng path vá»›i thuáº­t toÃ¡n tá»‘i Æ°u khÃ¡c.",
        "run_random_seed_caption": "Seed cá»§a láº§n cháº¡y ngáº«u nhiÃªn: `{seed}`. LÆ°u seed nÃ y Ä‘á»ƒ tÃ¡i láº­p Ä‘Ãºng láº§n cháº¡y.",
        "run_recorded_trajectory": "Quá»¹ Ä‘áº¡o ghi nháº­n (khÃ´ng pháº£i lá»i giáº£i)",
        "run_recorded_warning": "CÃ¡c bÆ°á»›c nÃ y lÃ  báº±ng chá»©ng hÃ nh vi há»£p lá»‡ cá»§a thuáº­t toÃ¡n, nhÆ°ng tráº¡ng thÃ¡i cuá»‘i chÆ°a tá»›i goal yÃªu cáº§u.",
        "compare_hero_title": "So sÃ¡nh hÃ nh vi solver vÃ  guarantee há»c thuáº­t",
        "compare_hero_desc": "Benchmark cho tháº¥y hÃ nh vi runtime; taxonomy tÃ¡ch solver chuáº©n cá»§a 15-puzzle khá»i contrast case vÃ  pháº§n má»Ÿ rá»™ng AI minh há»a.",
        "compare_hero_kicker": "So sÃ¡nh thuáº­t toÃ¡n",
        "compare_preset": "Preset benchmark",
        "compare_load_preset_state": "Táº£i tráº¡ng thÃ¡i preset",
        "compare_preset_caption": "Preset táº£i má»™t tráº¡ng thÃ¡i deterministic giáº£i Ä‘Æ°á»£c. Báº¡n váº«n cÃ³ thá»ƒ chá»‰nh thuáº­t toÃ¡n, heuristic, node cap vÃ  timeout trÆ°á»›c khi cháº¡y.",
        "compare_select_algorithms_desc": "Chá»n thuáº­t toÃ¡n Ä‘á»ƒ benchmark trÃªn tráº¡ng thÃ¡i báº¯t Ä‘áº§u hiá»‡n táº¡i.",
        "compare_standard_rankings_caption": "Báº£ng xáº¿p háº¡ng chuáº©n chá»‰ gá»“m solver tháº­t vÃ  local-search contrast case. CSP, uncertainty, online vÃ  game/chance náº±m trong Concept Lab vÃ¬ tiÃªu chÃ­ thÃ nh cÃ´ng vÃ  giáº£ Ä‘á»‹nh mÃ´i trÆ°á»ng khÃ´ng so sÃ¡nh trá»±c tiáº¿p Ä‘Æ°á»£c.",
        "compare_algorithms_from": "Thuáº­t toÃ¡n tá»« {group}",
        "compare_timeout": "Timeout (giÃ¢y)",
        "compare_fresh_seeds": "Táº¡o seed stochastic má»›i cho má»—i benchmark",
        "compare_fresh_seeds_help": "Má»—i thuáº­t toÃ¡n stochastic nháº­n má»™t seed riÃªng Ä‘Æ°á»£c ghi láº¡i. Táº¯t tÃ¹y chá»n nÃ y Ä‘á»ƒ dÃ¹ng seed cá»‘ Ä‘á»‹nh cho benchmark tÃ¡i láº­p.",
        "compare_fixed_seed": "Seed benchmark cá»‘ Ä‘á»‹nh",
        "compare_recorded_seeds": "Seed stochastic Ä‘Ã£ ghi nháº­n - {seeds}",
        "theory_hero_title": "LÃ½ thuyáº¿t, PEAS vÃ  khung báº£o vá»‡",
        "theory_hero_desc": "DÃ¹ng trang nÃ y Ä‘á»ƒ giáº£i thÃ­ch mÃ´ hÃ¬nh agent, guarantee thuáº­t toÃ¡n, cáº¥u trÃºc dá»¯ liá»‡u, Ä‘á»™ phá»©c táº¡p vÃ  vÃ¬ sao má»™t sá»‘ phÆ°Æ¡ng phÃ¡p chá»‰ lÃ  pháº§n má»Ÿ rá»™ng há»c thuáº­t.",
        "theory_hero_kicker": "TÃ i liá»‡u há»c thuáº­t",
        
        # Sidebar
        "sb_title": "Báº£ng Äiá»u Khiá»ƒn AI",
        "sb_start_state": "Tráº¡ng thÃ¡i Báº¯t Ä‘áº§u",
        "sb_input_method": "PhÆ°Æ¡ng thá»©c nháº­p",
        "sb_random": "Ngáº«u nhiÃªn (Scramble)",
        "sb_manual": "Nháº­p thá»§ cÃ´ng",
        "sb_depth": "Äá»™ sÃ¢u xÃ¡o trá»™n",
        "sb_seed": "Háº¡t giá»‘ng (Seed)",
        "sb_generate": "Táº¡o ngáº«u nhiÃªn",
        "sb_parse": "PhÃ¢n tÃ­ch Ä‘áº§u vÃ o",
        "sb_reset_goal": "Äáº·t láº¡i vá» ÄÃ­ch",
        "sb_solvable": "Tráº¡ng thÃ¡i giáº£i Ä‘Æ°á»£c",
        "sb_unsolvable": "KhÃ´ng thá»ƒ giáº£i. TrÃ¡o 2 Ã´ Ä‘á»ƒ giáº£i Ä‘Æ°á»£c.",
        "sb_sample_img": "áº¢nh xáº¿p hÃ¬nh máº«u",
        "sb_builtin": "áº¢nh cÃ³ sáºµn",
        "sb_load_img": "Táº£i áº£nh máº«u",
        "sb_show_num": "Hiá»ƒn thá»‹ sá»‘ trÃªn áº£nh (Helper)",
        "sb_curr_start": "Tráº¡ng thÃ¡i báº¯t Ä‘áº§u hiá»‡n táº¡i",
        "sb_goal_state": "Tráº¡ng thÃ¡i ÄÃ­ch",
        "sb_goal_manual_desc": "Nháº­p 16 sá»‘ cho ma tráº­n Ä‘Ã­ch (0=Ã´ trá»‘ng)",
        "sb_parse_goal": "PhÃ¢n tÃ­ch ÄÃ­ch",
        "sb_goal_parse_success": "ÄÃ£ cáº­p nháº­t tráº¡ng thÃ¡i Ä‘Ã­ch!",
        "sb_standard_goal": "ÄÃ­ch chuáº©n",
        "sb_curr_goal": "Tráº¡ng thÃ¡i Ä‘Ã­ch hiá»‡n táº¡i",
        
        # Tab Play
        "play_title": "TrÃ² chÆ¡i 15-Puzzle | BÃ n cá» TÆ°Æ¡ng tÃ¡c",
        "play_start": "Báº£ng báº¯t Ä‘áº§u",
        "play_goal": "Báº£ng Ä‘Ã­ch",
        "play_custom_img": "Sá»­ dá»¥ng áº£nh tÃ¹y chá»n",
        "play_upload_desc": "Táº£i lÃªn má»™t hÃ¬nh áº£nh báº¥t ká»³ Ä‘á»ƒ cáº¯t thÃ nh 15 máº£nh ghÃ©p xáº¿p hÃ¬nh.",
        "play_upload_label": "Chá»n file áº£nh",
        "play_remove_img": "XÃ³a áº£nh tÃ¹y chá»n",
        "play_manual": "ChÆ¡i báº±ng tay",
        "play_manual_desc": "Nháº¥p vÃ o báº¥t ká»³ Ã´ sá»‘ nÃ o ká» Ã´ trá»‘ng Ä‘á»ƒ trÆ°á»£t.",
        "play_moves": "Sá»‘ bÆ°á»›c Ä‘i",
        "play_manhattan": "Khoáº£ng cÃ¡ch Manhattan",
        "play_tiles_correct": "Sá»‘ Ã´ Ä‘Ãºng vá»‹ trÃ­",
        "play_reset_board": "Äáº·t láº¡i bÃ n chÆ¡i",
        "play_undo": "HoÃ n tÃ¡c bÆ°á»›c cuá»‘i",
        "play_challenge_title": "Cháº¿ Ä‘á»™ thá»­ thÃ¡ch há»c thuáº­t",
        "play_challenge_desc": "A* vá»›i Linear Conflict admissible chá»©ng minh khoáº£ng cÃ¡ch tá»‘i Æ°u. Lá»‹ch sá»­ chÆ¡i Ä‘Æ°á»£c kiá»ƒm chá»©ng tá»«ng bÆ°á»›c, rá»“i chá»‰ cháº¥m Ä‘iá»ƒm sau khi tá»›i goal.",
        "play_prove_optimal": "Chá»©ng minh sá»‘ bÆ°á»›c tá»‘i Æ°u",
        "play_computing_certificate": "Äang tÃ­nh chá»©ng chá»‰ tá»‘i Æ°u...",
        "play_cert_validation_failed": "Kiá»ƒm chá»©ng lá»‹ch sá»­ chÆ¡i tháº¥t báº¡i: {error}",
        "play_cert_player_run": "LÆ°á»£t chÆ¡i",
        "play_cert_recorded_moves": "Sá»‘ bÆ°á»›c ghi nháº­n",
        "play_cert_reached_goal": "Tá»›i Ä‘Ã­ch?",
        "play_cert_assistance": "Há»— trá»£",
        "play_cert_legal": "Há»£p lá»‡",
        "play_cert_invalid": "KhÃ´ng há»£p lá»‡",
        "play_cert_ai_assisted": "CÃ³ AI há»— trá»£",
        "play_cert_unassisted": "Tá»± chÆ¡i",
        "play_cert_verified": "Chá»©ng chá»‰ tá»‘i Æ°u Ä‘Ã£ xÃ¡c minh: má»i bÆ°á»›c Ä‘i há»£p lá»‡ vÃ  chi phÃ­ lá»i giáº£i tá»‘i Æ°u Ä‘Ã£ chá»©ng minh lÃ  {cost}.",
        "play_cert_failed": "Chá»©ng chá»‰ lÆ°á»£t chÆ¡i tháº¥t báº¡i: {message}",
        "play_cert_in_progress": "LÆ°á»£t chÆ¡i há»£p lá»‡ nhÆ°ng váº«n Ä‘ang diá»…n ra. HÃ£y Ä‘Æ°a báº£ng tá»›i goal trÆ°á»›c khi so sÃ¡nh sá»‘ bÆ°á»›c vá»›i nghiá»‡m tá»‘i Æ°u.",
        "play_score_failed": "TÃ­nh Ä‘iá»ƒm tháº¥t báº¡i: {error}",
        "play_score_optimal_moves": "Sá»‘ bÆ°á»›c tá»‘i Æ°u",
        "play_score_your_moves": "Sá»‘ bÆ°á»›c cá»§a báº¡n",
        "play_score_gap": "Äá»™ lá»‡ch bÆ°á»›c",
        "play_score_efficiency": "Hiá»‡u suáº¥t",
        "play_score_optimal_unassisted": "LÆ°á»£t chÆ¡i hoÃ n thÃ nh cá»§a báº¡n khá»›p Ä‘Ãºng sá»‘ bÆ°á»›c tá»‘i Æ°u Ä‘Ã£ chá»©ng minh.",
        "play_score_optimal_assisted": "LÆ°á»£t chÆ¡i cÃ³ AI há»— trá»£ khá»›p sá»‘ bÆ°á»›c tá»‘i Æ°u. ÄÃ¢y lÃ  minh chá»©ng Ä‘Æ°á»ng Ä‘i solver, khÃ´ng pháº£i báº±ng chá»©ng tá»‘i Æ°u khi tá»± chÆ¡i.",
        "play_score_longer": "LÆ°á»£t chÆ¡i {mode} há»£p lá»‡ nhÆ°ng dÃ i hÆ¡n tá»‘i Æ°u {gap} bÆ°á»›c.",
        "play_no_opt_cert": "ChÆ°a táº¡o Ä‘Æ°á»£c chá»©ng chá»‰ tá»‘i Æ°u: {message}",
        "slide_right": "TrÆ°á»£t sang pháº£i",
        "slide_left": "TrÆ°á»£t sang trÃ¡i",
        "slide_down": "TrÆ°á»£t xuá»‘ng",
        "slide_up": "TrÆ°á»£t lÃªn",
        "play_ai_solver": "Giáº£i tá»± Ä‘á»™ng báº±ng AI",
        "play_ai_desc": "Sá»­ dá»¥ng thuáº­t toÃ¡n **A* Search** vá»›i Heuristic **Manhattan Distance** tÃ¬m lá»i giáº£i tá»‘i Æ°u.",
        "play_ai_solve_btn": "TÃ¬m lá»i giáº£i báº±ng AI",
        "play_ai_clear_btn": "Há»§y lá»i giáº£i AI",
        "play_ai_running": "AI Ä‘ang tÃ­nh toÃ¡n...",
        "play_ai_solved_msg": "ÄÃ£ tÃ¬m tháº¥y lá»i giáº£i tá»‘i Æ°u gá»“m {steps} bÆ°á»›c!",
        "play_ai_solved_info": "Lá»i giáº£i tá»‘i Æ°u A*: **{steps} bÆ°á»›c** | Thá»i gian tÃ­nh: **{time:.4f}s** | Sá»‘ nÃºt má»Ÿ rá»™ng: **{expanded}** | Max Frontier: **{max_f}**",
        "play_ai_already_goal": "Báº£ng Ä‘Ã£ á»Ÿ tráº¡ng thÃ¡i Ä‘Ã­ch rá»“i!",
        "play_ai_unsolvable": "Tráº¡ng thÃ¡i hiá»‡n táº¡i khÃ´ng thá»ƒ giáº£i Ä‘Æ°á»£c!",
        "play_prev_step": "BÆ°á»›c trÆ°á»›c",
        "play_next_step": "BÆ°á»›c tiáº¿p",
        "play_auto_run": "Cháº¡y tá»± Ä‘á»™ng",
        "play_stop_run": "Dá»«ng",
        "play_curr_step": "BÆ°á»›c hiá»‡n táº¡i",
        "play_action_performed": "HÃ nh Ä‘á»™ng vá»«a thá»±c hiá»‡n (bÆ°á»›c {step}/{total}): **{act}**",
        "play_auto_done": "ÄÃ£ hoÃ n thÃ nh giáº£i Ä‘á»‘ tá»± Ä‘á»™ng báº±ng AI!",
        "play_academic_analysis": "PhÃ¢n tÃ­ch há»c thuáº­t / Academic Analysis",
        
        # Tab Run Algorithm
        "run_title": "Cháº¡y Thuáº­t toÃ¡n AI",
        "run_group": "NhÃ³m thuáº­t toÃ¡n",
        "run_algo": "Thuáº­t toÃ¡n",
        "run_heuristic": "Heuristic chá»n",
        "run_params": "Tham sá»‘ cháº¡y",
        "run_max_nodes": "Giá»›i háº¡n sá»‘ Node",
        "run_max_depth": "Äá»™ sÃ¢u tá»‘i Ä‘a / Äá»™ sÃ¢u cÃ¢y game",
        "run_timeout": "Thá»i gian chá» (giÃ¢y)",
        "run_action_order": "Thá»© tá»± hÃ nh Ä‘á»™ng",
        "run_btn": "Khá»Ÿi cháº¡y thuáº­t toÃ¡n",
        "run_success": "Thuáº­t toÃ¡n {algo} Ä‘Ã£ tÃ¬m tháº¥y lá»i giáº£i!",
        "run_fail": "Tháº¥t báº¡i: {msg}",
        "run_sol_path": "ÄÆ°á»ng Ä‘i lá»i giáº£i",
        "run_trace_steps": "CÃ¡c bÆ°á»›c váº¿t (Trace Steps)",
        "run_detail": "Chi tiáº¿t Node / Frontier / Reached",
        "run_search_tree": "CÃ¢y TÃ¬m Kiáº¿m (Search Tree)",
        
        # Tab Step Trace
        "trace_title": "Trace Tá»«ng BÆ°á»›c Thuáº­t ToÃ¡n",
        "trace_info": "HÃ£y cháº¡y thuáº­t toÃ¡n Ä‘á»ƒ hiá»ƒn thá»‹ báº£ng trace chi tiáº¿t.",
        "trace_export": "Xuáº¥t báº£ng váº¿t dÆ°á»›i dáº¡ng CSV",
        "trace_result_title": "Trace: {algorithm}",
        "trace_empty_result": "Láº§n cháº¡y nÃ y khÃ´ng ghi nháº­n sá»± kiá»‡n trace. HÃ£y chá»n solver cÃ³ má»Ÿ rá»™ng node hoáº·c tÄƒng giá»›i háº¡n cháº¡y.",
        "trace_notation_help": "KÃ½ hiá»‡u node: `(A, R, g=1, h=10, f=11, cha=B)` nghÄ©a lÃ  node A sinh bá»Ÿi hÃ nh Ä‘á»™ng R, cÃ³ cost g, heuristic h, evaluation f vÃ  cha B.",
        "trace_detail_title": "Chi tiáº¿t Node / Frontier / Reached",
        "trace_tree_title": "CÃ¢y tÃ¬m kiáº¿m",
        "trace_download_csv": "Táº£i CSV trace",
        
        # Tab Compare
        "compare_title": "So SÃ¡nh Hiá»‡u NÄƒng Thuáº­t ToÃ¡n",
        "compare_desc": "Chá»n cÃ¡c thuáº­t toÃ¡n Ä‘á»ƒ Ä‘o Ä‘áº¡c vÃ  so sÃ¡nh hiá»‡u nÄƒng trÃªn tráº¡ng thÃ¡i báº¯t Ä‘áº§u.",
        "compare_groups": "Chá»n nhÃ³m thuáº­t toÃ¡n",
        "compare_run_btn": "Báº¯t Ä‘áº§u Ä‘o hiá»‡u nÄƒng (Benchmark)",
        "compare_running": "Äang cháº¡y benchmark thuáº­t toÃ¡n...",
        "compare_done": "HoÃ n thÃ nh: {curr}/{total}",
        "compare_prop": "Báº£ng so sÃ¡nh thuá»™c tÃ­nh lÃ½ thuyáº¿t",
        
        # UI Components
        "mc_status": "Tráº¡ng thÃ¡i",
        "mc_solved": "ThÃ nh cÃ´ng (Solved)",
        "mc_failed": "Tháº¥t báº¡i (Failed)",
        "mc_path_len": "Äá»™ dÃ i Ä‘Æ°á»ng Ä‘i",
        "mc_runtime": "Thá»i gian cháº¡y",
        "mc_expanded": "Sá»‘ nÃºt má»Ÿ rá»™ng",
        "mc_cost": "Chi phÃ­ (Cost)",
        "mc_max_f": "Frontier lá»›n nháº¥t",
        "mc_reached_size": "KÃ­ch thÆ°á»›c Reached",
        "mc_depth": "Äá»™ sÃ¢u",
        "tc_no_trace": "KhÃ´ng cÃ³ dá»¯ liá»‡u trace.",
        "tc_step": "BÆ°á»›c",
        "tc_action": "HÃ nh Ä‘á»™ng",
        "tc_node": "NÃºt",
        "tc_parent": "NÃºt cha",
        "tc_frontier": "BiÃªn giá»›i (Frontier)",
        "tc_reached": "ÄÃ£ duyá»‡t (Reached)",
        "tc_frontier_size": "Cá»¡ Frontier",
        "tc_reached_size": "Cá»¡ Reached",
        "tc_temp": "Nhiá»‡t Ä‘á»™ (T)",
        "tc_prob": "XÃ¡c suáº¥t P(accept)",
        "tc_accepted": "Cháº¥p nháº­n",
        "tc_yes": "CÃ³",
        "tc_no": "KhÃ´ng",
        "tc_belief": "Belief State",
        "tc_type": "Loáº¡i node",
        "tc_reason": "LÃ½ do",
        "tc_showing": "Äang hiá»ƒn thá»‹ {curr} trÃªn tá»•ng sá»‘ {total} bÆ°á»›c",
        "det_no_detail": "Chi tiáº¿t Node/Frontier/Reached khÃ´ng kháº£ dá»¥ng cho thuáº­t toÃ¡n nÃ y. Chá»‰ há»— trá»£ BFS, DFS, UCS, IDS, Greedy, A*, IDA*.",
        "det_slider": "Chá»n bÆ°á»›c Ä‘á»ƒ kiá»ƒm tra chi tiáº¿t",
        "det_single_step": "Trace chá»‰ cÃ³ má»™t bÆ°á»›c; hiá»ƒn thá»‹ trá»±c tiáº¿p bÆ°á»›c Ä‘Ã³.",
        "det_curr_node": "NÃºt hiá»‡n táº¡i (Current Node)",
        "det_more": "... +{count} nÃºt khÃ¡c",
        "det_empty": "Trá»‘ng hoáº·c khÃ´ng ghi nháº­n",
        "det_not_captured": "KhÃ´ng Ä‘Æ°á»£c ghi nháº­n cho thuáº­t toÃ¡n nÃ y",
        "anim_title": "Hoáº¡t áº£nh Lá»i giáº£i",
        "anim_speed": "Tá»‘c Ä‘á»™ cháº¡y",
        "anim_per_step": "{sec}s má»—i bÆ°á»›c",
        "anim_goal": "Goal! ThÃ nh cÃ´ng",
        "anim_complete": "Hoáº¡t áº£nh Ä‘Ã£ cháº¡y xong!",
        "anim_prev": "BÆ°á»›c trÆ°á»›c",
        "anim_next": "BÆ°á»›c sau",
        "anim_reset": "Äáº·t láº¡i",
        "eval_title": "ÄÃ¡nh GiÃ¡ Há»c Thuáº­t (Academic Evaluation)",
        "eval_prop": "Thuá»™c tÃ­nh (Property)",
        "eval_val": "ThÃ´ng tin há»c thuáº­t (Academic Value)",
        "eval_complete": "TÃ­nh Ä‘áº§y Ä‘á»§ (Completeness)",
        "eval_optimal": "TÃ­nh tá»‘i Æ°u (Optimality)",
        "eval_time": "Äá»™ phá»©c táº¡p thá»i gian (Time Complexity)",
        "eval_space": "Äá»™ phá»©c táº¡p khÃ´ng gian (Space Complexity)",
        "eval_suit": "Äá»™ phÃ¹ há»£p 15-Puzzle (Suitability)",
        "eval_pros": "Æ¯u Ä‘iá»ƒm (Pros)",
        "eval_cons": "NhÆ°á»£c Ä‘iá»ƒm (Cons)",
        "eval_tips": "LÆ°u Ã½ Ã´n thi (Exam Tips)",
        "eval_not_found": "KhÃ´ng tÃ¬m tháº¥y dá»¯ liá»‡u Ä‘Ã¡nh giÃ¡ cho thuáº­t toÃ¡n nÃ y.",
        
        # Directions
        "dir_L": "TrÃ¡i (trÆ°á»£t Ã´ sá»‘ sang pháº£i)",
        "dir_R": "Pháº£i (trÆ°á»£t Ã´ sá»‘ sang trÃ¡i)",
        "dir_U": "LÃªn (trÆ°á»£t Ã´ sá»‘ xuá»‘ng dÆ°á»›i)",
        "dir_D": "Xuá»‘ng (trÆ°á»£t Ã´ sá»‘ lÃªn trÃªn)",
        "dir_Start": "Báº¯t Ä‘áº§u",
        "dir_Goal": "ÄÃ­ch",
        
        # Hand-Tracing Tab
        "ht_title": "Luyá»‡n Táº­p Cháº¡y Tay (Hand-Tracing Practice)",
        "ht_desc": "Cháº¿ Ä‘á»™ há»c thuáº­t giÃºp báº¡n táº­p cháº¡y tay thuáº­t toÃ¡n trÃªn giáº¥y vÃ  Ä‘á»‘i chiáº¿u káº¿t quáº£ tá»«ng bÆ°á»›c (Frontier, Reached, CÃ¢y tÃ¬m kiáº¿m) Ä‘á»ƒ chuáº©n bá»‹ cho ká»³ thi lÃ½ thuyáº¿t.",
        "ht_setup": "Thiáº¿t láº­p Thá»­ thÃ¡ch má»›i",
        "ht_scramble": "Äá»™ sÃ¢u tá»‘i Æ°u (Scramble Depth)",
        "ht_scramble_help": "NÃªn chá»n 1-3 bÆ°á»›c Ä‘á»ƒ cháº¡y tay trÃªn giáº¥y kháº£ thi (dÆ°á»›i 10 bÆ°á»›c).",
        "ht_order": "Thá»© tá»± hÃ nh Ä‘á»™ng sinh con (Action Order)",
        "ht_order_help": "Thá»© tá»± di chuyá»ƒn Ã´ trá»‘ng. Ráº¥t quan trá»ng Ä‘á»ƒ khá»›p Ä‘Ã¡p Ã¡n.",
        "ht_btn_generate": "Táº¡o Thá»­ ThÃ¡ch Má»›i",
        "ht_btn_cancel": "Há»§y thá»­ thÃ¡ch",
        "ht_cur_state": "Tráº¡ng thÃ¡i bÃ n cá» hiá»‡n táº¡i",
        "ht_state_start": "Báº¯t Ä‘áº§u (Start)",
        "ht_state_curr": "Äang xÃ©t (Current)",
        "ht_state_goal": "ÄÃ­ch (Goal)",
        "ht_curr_step": "BÆ°á»›c hiá»‡n táº¡i: {step}",
        "ht_success_msg": "ChÃºc má»«ng! Báº¡n Ä‘Ã£ hoÃ n thÃ nh xuáº¥t sáº¯c thá»­ thÃ¡ch cháº¡y tay!",
        "ht_table_title": "Báº£ng Trace Ä‘Ã¡p Ã¡n hoÃ n chá»‰nh cá»§a báº¡n:",
        "ht_tree_title": "CÃ¢y tÃ¬m kiáº¿m Ä‘Ã£ váº½:",
        "ht_btn_new": "Luyá»‡n táº­p thá»­ thÃ¡ch má»›i",
        "ht_decision": "Quyáº¿t Ä‘á»‹nh Cháº¡y Tay cá»§a báº¡n",
        "ht_decision_desc": "Dá»±a trÃªn thuáº­t toÃ¡n hiá»‡n táº¡i, **nÃºt nÃ o trong Frontier sáº½ Ä‘Æ°á»£c má»Ÿ rá»™ng tiáº¿p theo**?",
        "ht_choice": "Lá»±a chá»n {num}",
        "ht_choice_btn": "Má»Ÿ rá»™ng Lá»±a chá»n {num}",
        "ht_expanded_to": "HÃ nh Ä‘á»™ng dáº«n tá»›i: `{act}`",
        "ht_expand_success": "ChÃ­nh xÃ¡c! Báº¡n Ä‘Ã£ má»Ÿ rá»™ng Ä‘Ãºng node {num}.",
        "ht_expand_error": "Sai rá»“i! Báº¡n Ä‘Ã£ chá»n má»Ÿ rá»™ng nÃºt `{chosen}` ({chosen_val}). NhÆ°ng theo thuáº­t toÃ¡n {algo} vÃ  quy táº¯c giáº£i quyáº¿t cÃ¢n báº±ng {tb}, nÃºt Ä‘Ãºng pháº£i má»Ÿ rá»™ng lÃ  `{correct}` ({correct_val}). HÃ£y phÃ¢n tÃ­ch láº¡i Frontier vÃ  chá»n láº¡i.",
        "ht_frontier_title": "Frontier (BiÃªn giá»›i) - {count} nÃºt:",
        "ht_reached_title": "Reached (ÄÃ£ duyá»‡t) - {count} tráº¡ng thÃ¡i:",
        "ht_history_title": "Báº£ng Trace cá»§a báº¡n (Lá»‹ch sá»­ cÃ¡c bÆ°á»›c Ä‘Ãºng)",
        "ht_frontier_empty": "Frontier Ä‘Ã£ rá»—ng: khÃ´ng cÃ²n node Ä‘á»ƒ má»Ÿ rá»™ng. HÃ£y táº¡o thá»­ thÃ¡ch má»›i hoáº·c tÄƒng Ä‘á»™ sÃ¢u/Ä‘á»•i thá»© tá»± hÃ nh Ä‘á»™ng.",
        
        # Extra translations added for complete localization
        "sb_manual_desc": "Nháº­p 16 sá»‘ (0=Ã´ trá»‘ng, cÃ¡ch nhau báº±ng dáº¥u cÃ¡ch)",
        "sb_parse_success": "ÄÃ£ phÃ¢n tÃ­ch tráº¡ng thÃ¡i thÃ nh cÃ´ng!",
        "sb_parse_error": "Äáº§u vÃ o khÃ´ng há»£p lá»‡: {error}",
        "play_solvable_label": "Giáº£i Ä‘Æ°á»£c?",
        "play_img_loaded": "áº¢nh Ä‘Ã£ táº£i! ÄÃ£ táº¡o ra {count} máº£nh ghÃ©p.",
        "play_img_failed": "Táº£i áº£nh tháº¥t báº¡i. HÃ£y cháº¯c cháº¯n Ä‘Ã³ lÃ  file áº£nh há»£p lá»‡.",
        "play_target_preview": "áº¢nh Gá»‘c Xem TrÆ°á»›c",
        "play_preview_fail": "KhÃ´ng thá»ƒ táº¡o áº£nh xem trÆ°á»›c.",
        "play_preview_error": "Lá»—i táº£i xem trÆ°á»›c: {error}",
        "play_preview_none": "KhÃ´ng cÃ³ áº£nh xem trÆ°á»›c.",
        "play_solved_success": "ChÃºc má»«ng! Báº¡n Ä‘Ã£ giáº£i Ä‘Æ°á»£c cÃ¢u Ä‘á»‘ sau {moves} bÆ°á»›c!",
        "play_victory_1": "Chiáº¿n tháº¯ng! BÃ n hiá»‡n táº¡i Ä‘Ã£ khá»›p hoÃ n toÃ n vá»›i báº£ng Ä‘Ã­ch sau {moves} bÆ°á»›c.",
        "play_victory_2": "HoÃ n háº£o rá»“i! CÃ¡c Ã´ Ä‘Ã£ vá» Ä‘Ãºng vá»‹ trÃ­ giá»‘ng báº£ng bÃªn cáº¡nh sau {moves} bÆ°á»›c.",
        "play_victory_3": "Xuáº¥t sáº¯c! Báº¡n Ä‘Ã£ Ä‘Æ°a 15-puzzle vá» tráº¡ng thÃ¡i Ä‘Ã­ch trong {moves} bÆ°á»›c.",
        "play_victory_4": "ÄÃºng chuáº©n solver lab! Báº£ng cá»§a báº¡n Ä‘Ã£ trÃ¹ng vá»›i goal sau {moves} bÆ°á»›c.",
        "play_victory_5": "Puzzle Ä‘Ã£ Ä‘Æ°á»£c giáº£i! Táº¥t cáº£ máº£nh ghÃ©p khá»›p báº£ng Ä‘Ã­ch sau {moves} bÆ°á»›c.",
        "play_ai_solve_btn_full": "TÃ¬m lá»i giáº£i báº±ng AI (A* Manhattan)",
        "play_ai_error": "Lá»—i tÃ¬m kiáº¿m lá»i giáº£i: {error}",
        "play_curr_step_label": "BÆ°á»›c hiá»‡n táº¡i: {step}/{total}",
        "run_tie_breaker": "Quy táº¯c phÃ¡ vá»¡ cÃ¢n báº±ng (Tie-breaking)",
        "run_tie_breaker_help": "Quy táº¯c chá»n node khi chi phÃ­ f(n) hoáº·c g(n)/h(n) báº±ng nhau. Cá»±c ká»³ há»¯u Ã­ch Ä‘á»ƒ sinh viÃªn Ä‘á»‘i chiáº¿u khi cháº¡y tay.",
        "run_max_iter": "Sá»‘ láº§n láº·p tá»‘i Ä‘a (Max Iterations)",
        "run_seed": "Háº¡t giá»‘ng ngáº«u nhiÃªn (Random Seed)",
        "run_max_restarts": "Sá»‘ láº§n thá»­ láº¡i tá»‘i Ä‘a (Max Restarts)",
        "run_beam_width": "Äá»™ rá»™ng chÃ¹m tia (Beam Width)",
        "run_init_temp": "Nhiá»‡t Ä‘á»™ ban Ä‘áº§u (Initial Temp)",
        "run_cooling_rate": "Tá»‘c Ä‘á»™ lÃ m mÃ¡t (Cooling Rate)",
        "run_min_temp": "Nhiá»‡t Ä‘á»™ tá»‘i thiá»ƒu (Min Temp)",
        "run_success_prob": "XÃ¡c suáº¥t thÃ nh cÃ´ng (Success Prob)",
        "run_error_unsolvable": "Tráº¡ng thÃ¡i báº¯t Ä‘áº§u khÃ´ng giáº£i Ä‘Æ°á»£c. Vui lÃ²ng táº¡o tráº¡ng thÃ¡i giáº£i Ä‘Æ°á»£c.",
        "run_error_not_found": "KhÃ´ng tÃ¬m tháº¥y thuáº­t toÃ¡n {algo}.",
        "run_error_func_not_found": "KhÃ´ng tÃ¬m tháº¥y hÃ m giáº£i {func}.",
        "run_spinner_running": "Äang cháº¡y {algo}...",
        "run_error_exception": "Lá»—i khi cháº¡y {algo}: {error}",
        "compare_heuristic": "Heuristic dÃ¹ng Ä‘á»ƒ so sÃ¡nh",
        "compare_benchmark_title": "Äo Hiá»‡u NÄƒng Thuáº­t ToÃ¡n",
        "compare_analysis": "PhÃ¢n tÃ­ch so sÃ¡nh hiá»‡u nÄƒng",
        "compare_fastest": "Nhanh nháº¥t: **{algo}** ({time:.4f}s)",
        "compare_shortest": "ÄÆ°á»ng Ä‘i ngáº¯n nháº¥t: **{algo}** ({steps} bÆ°á»›c)",
        "compare_most_memory": "Tá»‘n bá»™ nhá»› nháº¥t: **{algo}** ({nodes} nodes)",
        "compare_no_data": "HÃ£y cháº¡y benchmark Ä‘á»ƒ hiá»ƒn thá»‹ báº£ng so sÃ¡nh.",
        "compare_optimal_col": "Tá»‘i Æ°u?",
        "compare_complete_col": "Äáº§y Ä‘á»§?",
        "compare_group_col": "NhÃ³m",
        "adv_mode": "Cháº¿ Ä‘á»™ NÃ¢ng cao",
        "adv_title": "Mô hình nâng cao 15-Puzzle",
        "adv_hero_title": "Mô phỏng môi trường AI và chấm điểm solver",
        "adv_hero_desc": "Các chế độ này cho thấy 15-puzzle có thể được tái mô hình hóa thành tournament scoring, CSP planning, uncertainty, online learning và game-tree reasoning.",
        "adv_hero_kicker": "Mô hình học thuật nâng cao",
        "adv_mode_prompt": "-- Chọn mô hình nâng cao --",
        "adv_model_select": "Thuật toán / Mô hình",
        "adv_select_mode_help": "Chọn một mô hình trong danh sách. AI-vs-AI Tournament chấm điểm hai solver trên cùng một bảng 15-puzzle; nó không biến 15-puzzle thành game đối kháng tự nhiên.",
        "academic_extension_warning": "Ranh giới học thuật: CSP, môi trường phức tạp, Minimax, Alpha-Beta và Expectimax là các phần mở rộng giáo dục. Chúng minh họa cách mô hình hóa bài toán AI khác, nhưng không phải solver tự nhiên cho 15-puzzle chuẩn, tất định, quan sát đầy đủ.",
        "tournament_title": "AI-vs-AI Tournament",
        "tournament_desc": "Đây là lớp chấm điểm trên các solver 15-puzzle chuẩn. Hai AI cùng giải một trạng thái; bản thân 15-puzzle vẫn là bài toán một tác nhân.",
        "tournament_agent_a_algorithm": "Thuật toán AI A",
        "tournament_agent_b_algorithm": "Thuật toán AI B",
        "tournament_agent_a_seed": "Seed AI A",
        "tournament_agent_b_seed": "Seed AI B",
        "tournament_rounds": "Số vòng",
        "tournament_round_depth": "Độ sâu scramble vòng thêm",
        "tournament_max_nodes": "Giới hạn node mỗi AI",
        "tournament_max_depth": "Độ sâu tối đa",
        "tournament_timeout": "Timeout mỗi AI",
        "tournament_base_seed": "Seed vòng đấu",
        "tournament_reference_heuristic": "Heuristic tham chiếu",
        "tournament_run": "Chạy AI-vs-AI Tournament",
        "tournament_empty_state": "Chọn hai solver rồi bấm chạy tournament để xem điểm, cost tối ưu tham chiếu, node mở rộng và lý do chấm điểm.",
        "tournament_winner": "Bên thắng",
        "tournament_round_label": "Vòng {number}",
        "tournament_round_skipped": "Bỏ qua vòng này vì A* tham chiếu chưa chứng minh được cost tối ưu.",
        "tournament_agent_col": "Tác nhân",
        "tournament_points_col": "Điểm",
        "tournament_optimal_cost_col": "Cost tối ưu",
        "tournament_excess_col": "Lệch cost",
        "tournament_nodes_col": "Node",
        "adv_time_horizon": "Giá»›i háº¡n thá»i gian (Time Horizon)",
        "adv_nondet_prob": "XÃ¡c suáº¥t khÃ´ng xÃ¡c Ä‘á»‹nh",
        "adv_belief_states": "Sá»‘ lÆ°á»£ng Belief States",
        "adv_max_steps": "Sá»‘ bÆ°á»›c tá»‘i Ä‘a",
        "adv_game_tree_depth": "Äá»™ sÃ¢u cÃ¢y trÃ² chÆ¡i",
        "adv_success_prob": "XÃ¡c suáº¥t dá»‹ch chuyá»ƒn thÃ nh cÃ´ng",
        "theory_title": "TÃ i Liá»‡u LÃ½ Thuyáº¿t & PhÃ¢n TÃ­ch PEAS",
        "theory_peas_title": "PhÃ¢n tÃ­ch PEAS cho Äáº¡i lÃ½ giáº£i 15-Puzzle",
        "theory_detail_title": "Chi tiáº¿t lÃ½ thuyáº¿t thuáº­t toÃ¡n",
        "theory_coming_soon": "Chi tiáº¿t lÃ½ thuyáº¿t cho {algo} sáº½ sá»›m Ä‘Æ°á»£c cáº­p nháº­t.",
        "theory_belongs_group": "Thuá»™c nhÃ³m thuáº­t toÃ¡n: {group}",
        "theory_peas_peas": "PhÃ¢n tÃ­ch PEAS",
    },
    "English": {
        # Navigation
        "nav_play": "Play Puzzle",
        "nav_run": "Run Algorithm",
        "nav_trace": "Step Trace",
        "nav_hand_trace": "Hand-Tracing Practice",
        "nav_compare": "Compare",
        "nav_theory": "PEAS Theory",
        "nav_advanced": "Advanced Mode",
        "demo_workflow": "Demo Workflow",
        "teaching_preset": "Teaching Preset",
        "teaching_preset_help": "Audited cases that make algorithm tradeoffs visible.",
        "load_teaching_preset": "Load Teaching Preset",
        "play_hero_title": "15-Puzzle AI Solver Lab",
        "play_hero_desc": "A final-exam dashboard for demonstrating PEAS, state-space search, heuristics, and the boundary between real solvers and educational extensions.",
        "play_hero_kicker": "AI final exam dashboard",
        "exam_step_label": "Step",
        "exam_tab_play": "Play",
        "exam_tab_run": "Run",
        "exam_tab_compare": "Compare",
        "exam_tab_theory": "Theory/PEAS",
        "exam_tab_hand": "Hand-Tracing",
        "exam_step_play_title": "Set state",
        "exam_step_play_note": "Load a preset or inspect solvability.",
        "exam_step_run_title": "Trace one solver",
        "exam_step_run_note": "Explain frontier, reached, and guarantees.",
        "exam_step_compare_title": "Measure tradeoffs",
        "exam_step_compare_note": "Use seed, depth, heuristic, and caveat.",
        "exam_step_theory_title": "Defend model",
        "exam_step_theory_note": "Show PEAS, proofs, taxonomy, and limits.",
        "exam_step_hand_title": "Verify by hand",
        "exam_step_hand_note": "Practice expansion order and tie-breaking.",
        "run_hero_title": "Run one algorithm with academic context",
        "run_hero_desc": "Inspect guarantees, environment assumptions, trace data, and why the selected method is or is not a natural 15-puzzle solver.",
        "run_hero_kicker": "Single algorithm analysis",
        "run_model_success_no_goal": "{algo} produced a successful model result, but it did not certify a standard path to the requested goal.",
        "run_fresh_seed": "Fresh random seed each run",
        "run_fresh_seed_help": "Enabled: each run samples a new stochastic trajectory. Disabled: reuse a fixed seed for reproducible academic comparison.",
        "run_fixed_seed": "Fixed Random Seed",
        "run_deterministic_caption": "Deterministic run: identical state, parameters, action order, and tie-breaker may legitimately produce the same path as another optimal algorithm.",
        "run_random_seed_caption": "Randomized run seed: `{seed}`. Save this seed to reproduce this exact run.",
        "run_recorded_trajectory": "Recorded Trajectory (not a solution)",
        "run_recorded_warning": "These moves are legal evidence of the algorithm's behavior, but the final state did not reach the requested goal.",
        "compare_hero_title": "Compare solver behavior and academic guarantees",
        "compare_hero_desc": "Benchmark results show runtime behavior; the taxonomy table separates standard 15-puzzle solvers from contrast cases and illustrative AI extensions.",
        "compare_hero_kicker": "Algorithm comparison",
        "compare_preset": "Benchmark preset",
        "compare_load_preset_state": "Load preset state",
        "compare_preset_caption": "Preset loads a deterministic solvable state. You can still adjust algorithms, heuristic, node cap, and timeout before running.",
        "compare_select_algorithms_desc": "Select algorithms to benchmark against the current start state.",
        "compare_standard_rankings_caption": "Standard rankings include real solvers and local-search contrast cases only. CSP, uncertainty, online, and game/chance models remain in Concept Lab because their success criteria and environment assumptions are not directly comparable.",
        "compare_algorithms_from": "Algorithms from {group}",
        "compare_timeout": "Timeout (s)",
        "compare_fresh_seeds": "Fresh stochastic seeds each benchmark",
        "compare_fresh_seeds_help": "Each stochastic algorithm receives a distinct recorded seed. Disable this to reuse a fixed seed for a reproducible benchmark.",
        "compare_fixed_seed": "Fixed benchmark seed",
        "compare_recorded_seeds": "Recorded stochastic seeds - {seeds}",
        "theory_hero_title": "Theory notes, PEAS, and exam framing",
        "theory_hero_desc": "Use this page to explain the agent model, algorithm guarantees, data structures, complexity, and why some methods are only academic extensions.",
        "theory_hero_kicker": "Academic reference",
        
        # Sidebar
        "sb_title": "AI Control Panel",
        "sb_start_state": "Start State",
        "sb_input_method": "Input method",
        "sb_random": "Random (Scramble)",
        "sb_manual": "Manual Input",
        "sb_depth": "Scramble Depth",
        "sb_seed": "Seed",
        "sb_generate": "Generate Random",
        "sb_parse": "Parse Input",
        "sb_reset_goal": "Reset to Goal",
        "sb_solvable": "Solvable state",
        "sb_unsolvable": "Unsolvable. Swap 2 tiles to fix.",
        "sb_sample_img": "Sample Image Mode",
        "sb_builtin": "Built-in images",
        "sb_load_img": "Load Sample Image",
        "sb_show_num": "Show numbers on image (Helper)",
        "sb_curr_start": "Current Start State",
        "sb_goal_state": "Goal State",
        "sb_goal_manual_desc": "Enter 16 numbers for the goal matrix (0=blank)",
        "sb_parse_goal": "Parse Goal",
        "sb_goal_parse_success": "Goal state updated!",
        "sb_standard_goal": "Standard Goal",
        "sb_curr_goal": "Current Goal State",
        
        # Tab Play
        "play_title": "15-Puzzle | Interactive Board",
        "play_start": "Start State",
        "play_goal": "Goal State",
        "play_custom_img": "Custom Image Upload",
        "play_upload_desc": "Upload any image to split it into 15 puzzle tiles.",
        "play_upload_label": "Upload puzzle image",
        "play_remove_img": "Remove Custom Image",
        "play_manual": "Manual Play",
        "play_manual_desc": "Click any tile adjacent to the blank space to slide it.",
        "play_moves": "Moves Played",
        "play_manhattan": "Manhattan Distance",
        "play_tiles_correct": "Tiles in Goal Position",
        "play_reset_board": "Reset Board",
        "play_undo": "Undo Last Move",
        "play_challenge_title": "Academic Challenge Mode",
        "play_challenge_desc": "A* with admissible Linear Conflict proves the optimal distance. Your recorded play history is certified step-by-step, then scored only after it reaches the goal.",
        "play_prove_optimal": "Prove Optimal Move Count",
        "play_computing_certificate": "Computing an optimal certificate...",
        "play_cert_validation_failed": "Player-run validation failed: {error}",
        "play_cert_player_run": "Player Run",
        "play_cert_recorded_moves": "Recorded Moves",
        "play_cert_reached_goal": "Reached Goal",
        "play_cert_assistance": "Assistance",
        "play_cert_legal": "Legal",
        "play_cert_invalid": "Invalid",
        "play_cert_ai_assisted": "AI-assisted",
        "play_cert_unassisted": "Unassisted",
        "play_cert_verified": "Optimality certificate verified: every move is legal and the proven solution cost is {cost}.",
        "play_cert_failed": "Player-run certificate failed: {message}",
        "play_cert_in_progress": "Player-run certificate verified, but the current run is still in progress. Finish the puzzle before comparing your move count with the optimum.",
        "play_score_failed": "Score computation failed: {error}",
        "play_score_optimal_moves": "Optimal Moves",
        "play_score_your_moves": "Your Moves",
        "play_score_gap": "Move Gap",
        "play_score_efficiency": "Efficiency",
        "play_score_optimal_unassisted": "Your completed run matches the proven optimal move count.",
        "play_score_optimal_assisted": "The completed AI-assisted run matches the optimal move count. This demonstrates the solver path, not unassisted player optimality.",
        "play_score_longer": "The completed {mode} run is legal but {gap} move(s) longer than optimal.",
        "play_no_opt_cert": "No optimality certificate produced: {message}",
        "slide_right": "Slide right",
        "slide_left": "Slide left",
        "slide_down": "Slide down",
        "slide_up": "Slide up",
        "play_ai_solver": "AI Auto-Solver",
        "play_ai_desc": "Uses **A* Search** with **Manhattan Distance** heuristic to find the optimal path.",
        "play_ai_solve_btn": "Find Solution via AI",
        "play_ai_clear_btn": "Discard AI Solution",
        "play_ai_running": "AI is computing...",
        "play_ai_solved_msg": "Found optimal solution in {steps} steps!",
        "play_ai_solved_info": "A* Optimal Solution: **{steps} steps** | Runtime: **{time:.4f}s** | Nodes Expanded: **{expanded}** | Max Frontier: **{max_f}**",
        "play_ai_already_goal": "Board is already at goal state!",
        "play_ai_unsolvable": "Current board state is unsolvable!",
        "play_prev_step": "Prev Step",
        "play_next_step": "Next Step",
        "play_auto_run": "Auto Play",
        "play_stop_run": "Pause",
        "play_curr_step": "Current Step",
        "play_action_performed": "Action performed (step {step}/{total}): **{act}**",
        "play_auto_done": "AI Auto-solving complete!",
        "play_academic_analysis": "Academic Analysis & State-Space",
        
        # Tab Run Algorithm
        "run_title": "Run Search Algorithm",
        "run_group": "Algorithm Group",
        "run_algo": "Algorithm",
        "run_heuristic": "Heuristic Function",
        "run_params": "Search Parameters",
        "run_max_nodes": "Max Nodes Limit",
        "run_max_depth": "Max Depth / Game Tree Depth",
        "run_timeout": "Timeout (seconds)",
        "run_action_order": "Action Order (Blank Move)",
        "run_btn": "Run Search Algorithm",
        "run_success": "{algo} found a solution!",
        "run_fail": "Failed: {msg}",
        "run_sol_path": "Solution Path",
        "run_trace_steps": "Trace Steps",
        "run_detail": "Node / Frontier / Reached Detail",
        "run_search_tree": "Search Tree Visualization",
        
        # Tab Step Trace
        "trace_title": "Step-by-Step Search Trace",
        "trace_info": "Run an algorithm first to see its step-by-step trace.",
        "trace_export": "Export Trace as CSV",
        "trace_result_title": "Trace: {algorithm}",
        "trace_empty_result": "This run did not record trace events. Choose a node-expanding solver or increase the run limits.",
        "trace_notation_help": "Node notation: `(A, R, g=1, h=10, f=11, parent=B)` means node A was generated by action R with path cost g, heuristic h, evaluation f, and parent B.",
        "trace_detail_title": "Node / Frontier / Reached Detail",
        "trace_tree_title": "Search Tree",
        "trace_download_csv": "Download Trace CSV",
        
        # Tab Compare
        "compare_title": "Compare Algorithm Performance",
        "compare_desc": "Select algorithms to benchmark and compare on the current start state.",
        "compare_groups": "Algorithm Groups",
        "compare_run_btn": "Run Performance Benchmark",
        "compare_running": "Running algorithm benchmark...",
        "compare_done": "Done: {curr}/{total}",
        "compare_prop": "Theoretical Properties Comparison Table",
        
        # UI Components
        "mc_status": "Status",
        "mc_solved": "Solved",
        "mc_failed": "Failed",
        "mc_path_len": "Path Length",
        "mc_runtime": "Runtime",
        "mc_expanded": "Nodes Expanded",
        "mc_cost": "Cost",
        "mc_max_f": "Max Frontier",
        "mc_reached_size": "Reached Size",
        "mc_depth": "Depth",
        "tc_no_trace": "No trace data available.",
        "tc_step": "Step",
        "tc_action": "Action",
        "tc_node": "Node",
        "tc_parent": "Parent",
        "tc_frontier": "Frontier Size",
        "tc_reached": "Reached Size",
        "tc_frontier_size": "Frontier Count",
        "tc_reached_size": "Reached Count",
        "tc_temp": "Temperature (T)",
        "tc_prob": "P(accept)",
        "tc_accepted": "Accepted",
        "tc_yes": "Yes",
        "tc_no": "No",
        "tc_belief": "Belief State",
        "tc_type": "Node Type",
        "tc_reason": "Reason",
        "tc_showing": "Showing {curr} of {total} steps",
        "det_no_detail": "Node/Frontier/Reached detail not available for this algorithm. Only available for BFS, DFS, UCS, IDS, Greedy, A*, IDA*.",
        "det_slider": "Select step to inspect",
        "det_single_step": "Trace has one step; showing that step directly.",
        "det_curr_node": "Current Node",
        "det_more": "... +{count} more nodes",
        "det_empty": "Empty or not captured",
        "det_not_captured": "Not captured for this algorithm",
        "anim_title": "Solution Animation",
        "anim_speed": "Playback Speed",
        "anim_per_step": "{sec}s per step",
        "anim_goal": "Goal reached!",
        "anim_complete": "Solution animation complete!",
        "anim_prev": "Prev",
        "anim_next": "Next",
        "anim_reset": "Reset",
        "eval_title": "Academic Evaluation",
        "eval_prop": "Property",
        "eval_val": "Academic Value",
        "eval_complete": "Completeness",
        "eval_optimal": "Optimality",
        "eval_time": "Time Complexity",
        "eval_space": "Space Complexity",
        "eval_suit": "15-Puzzle Suitability",
        "eval_pros": "Pros",
        "eval_cons": "Cons",
        "eval_tips": "Exam Tips",
        "eval_not_found": "No academic evaluation data found for this algorithm.",
        
        # Directions
        "dir_L": "Left (slides tile right)",
        "dir_R": "Right (slides tile left)",
        "dir_U": "Up (slides tile down)",
        "dir_D": "Down (slides tile up)",
        "dir_Start": "Start",
        "dir_Goal": "Goal",
        
        # Hand-Tracing Tab
        "ht_title": "Hand-Tracing Practice Mode",
        "ht_desc": "An academic mode to practice trace steps on paper and verify your answers (Frontier, Reached, Search Tree) for exam preparation.",
        "ht_setup": "Setup New Challenge",
        "ht_scramble": "Optimal Path Length (Scramble Depth)",
        "ht_scramble_help": "Recommend 1-3 steps to keep manual tracing realistic on paper (under 10 steps total).",
        "ht_order": "Blank Move Order (Action Order)",
        "ht_order_help": "Order of generating children. Critical to match answers.",
        "ht_btn_generate": "Generate New Challenge",
        "ht_btn_cancel": "Cancel Challenge",
        "ht_cur_state": "Current Board State",
        "ht_state_start": "Start State",
        "ht_state_curr": "Current State",
        "ht_state_goal": "Goal State",
        "ht_curr_step": "Current Step: {step}",
        "ht_success_msg": "Congratulations! You have successfully solved the hand-tracing challenge!",
        "ht_table_title": "Your Completed Tracing Table:",
        "ht_tree_title": "Search Tree Generated:",
        "ht_btn_new": "Start New Practice",
        "ht_decision": "Your Hand-Tracing Choice",
        "ht_decision_desc": "Based on the search strategy, **which node in the Frontier will be expanded next**?",
        "ht_choice": "Option {num}",
        "ht_choice_btn": "Expand Option {num}",
        "ht_expanded_to": "Action leading to: `{act}`",
        "ht_expand_success": "Correct choice! You expanded node {num}.",
        "ht_expand_error": "Incorrect! You selected node `{chosen}` ({chosen_val}). But according to **{algo}** and tie-breaking rule **{tb}**, the correct node to expand is `{correct}` ({correct_val}). Analyze the Frontier and try again.",
        "ht_frontier_title": "Frontier - {count} nodes:",
        "ht_reached_title": "Reached - {count} states:",
        "ht_history_title": "Your Tracing Table (Correct Steps History)",
        "ht_frontier_empty": "Frontier is empty: no node remains to expand. Generate a new challenge or adjust depth/action order.",
        
        # Extra translations added for complete localization
        "sb_manual_desc": "Enter 16 numbers (0=blank, space-separated)",
        "sb_parse_success": "State parsed successfully!",
        "sb_parse_error": "Invalid input: {error}",
        "play_solvable_label": "Is Solvable?",
        "play_img_loaded": "Image loaded! {count} tile pieces created.",
        "play_img_failed": "Failed to load image. Make sure it's a valid image file.",
        "play_target_preview": "Target Preview",
        "play_preview_fail": "Preview could not be generated.",
        "play_preview_error": "Error loading preview: {error}",
        "play_preview_none": "No preview available.",
        "play_solved_success": "Congratulations! You solved the puzzle in {moves} moves!",
        "play_victory_1": "Victory! The current board matches the goal board after {moves} moves.",
        "play_victory_2": "Perfect! Every tile is in the same position as the goal board after {moves} moves.",
        "play_victory_3": "Excellent! You solved the 15-puzzle in {moves} moves.",
        "play_victory_4": "Solver-lab clean! Your board reached the goal state after {moves} moves.",
        "play_victory_5": "Puzzle solved! All tiles match the goal board after {moves} moves.",
        "play_ai_solve_btn_full": "Find Solution via AI (A* Manhattan)",
        "play_ai_error": "Error finding solution: {error}",
        "play_curr_step_label": "Current Step: {step}/{total}",
        "run_tie_breaker": "Tie-breaking Rule",
        "run_tie_breaker_help": "Rule to select a node when evaluations are equal. Extremely useful for students to compare with manual tracing.",
        "run_max_iter": "Max Iterations",
        "run_seed": "Random Seed",
        "run_max_restarts": "Max Restarts",
        "run_beam_width": "Beam Width",
        "run_init_temp": "Initial Temp",
        "run_cooling_rate": "Cooling Rate",
        "run_min_temp": "Min Temp",
        "run_success_prob": "Success Probability",
        "run_error_unsolvable": "Current state is NOT solvable. Please generate a solvable state.",
        "run_error_not_found": "Algorithm {algo} not found.",
        "run_error_func_not_found": "Solver function {func} not found.",
        "run_spinner_running": "Running {algo}...",
        "run_error_exception": "Error running {algo}: {error}",
        "compare_heuristic": "Heuristic for comparison",
        "compare_benchmark_title": "Compare Algorithm Performance",
        "compare_analysis": "Performance Comparison Analysis",
        "compare_fastest": "Fastest: **{algo}** ({time:.4f}s)",
        "compare_shortest": "Shortest path: **{algo}** ({steps} steps)",
        "compare_most_memory": "Most memory: **{algo}** ({nodes} nodes)",
        "compare_no_data": "Run benchmarks to see the comparison table.",
        "compare_optimal_col": "Optimal?",
        "compare_complete_col": "Complete?",
        "compare_group_col": "Group",
        "adv_mode": "Advanced Mode",
        "adv_title": "15-Puzzle Advanced Models",
        "adv_hero_title": "Extended AI environment and solver-scoring demonstrations",
        "adv_hero_desc": "These modes show how the 15-puzzle can be reframed for tournament scoring, CSP planning, uncertainty, online learning, and game-tree reasoning.",
        "adv_hero_kicker": "Advanced academic models",
        "adv_mode_prompt": "-- Select an advanced model --",
        "adv_model_select": "Algorithm / Model",
        "adv_select_mode_help": "Choose a model above. AI-vs-AI Tournament scores two solver agents on the same 15-puzzle board; it does not turn the puzzle into a natural adversarial game.",
        "academic_extension_warning": "Academic boundary: CSP, complex-environment, Minimax, Alpha-Beta, and Expectimax modes are educational extensions. They explain alternate AI problem formulations, but they are not natural solvers for the standard deterministic, fully observable 15-puzzle.",
        "tournament_title": "AI-vs-AI Tournament",
        "tournament_desc": "This is a scoring layer over standard 15-puzzle solvers. Both AI agents solve the same puzzle state; the board itself remains single-agent.",
        "tournament_agent_a_algorithm": "AI A algorithm",
        "tournament_agent_b_algorithm": "AI B algorithm",
        "tournament_agent_a_seed": "AI A seed",
        "tournament_agent_b_seed": "AI B seed",
        "tournament_rounds": "Rounds",
        "tournament_round_depth": "Extra-round scramble depth",
        "tournament_max_nodes": "Max nodes per AI",
        "tournament_max_depth": "Max depth",
        "tournament_timeout": "Timeout per AI",
        "tournament_base_seed": "Round seed",
        "tournament_reference_heuristic": "Reference heuristic",
        "tournament_run": "Run AI-vs-AI tournament",
        "tournament_empty_state": "Choose two solvers and run the tournament to see points, reference optimal cost, expanded nodes, and scoring reasons.",
        "tournament_winner": "Winner",
        "tournament_round_label": "Round {number}",
        "tournament_round_skipped": "Round skipped because the A* reference did not prove optimal cost.",
        "tournament_agent_col": "Agent",
        "tournament_points_col": "Points",
        "tournament_optimal_cost_col": "Optimal cost",
        "tournament_excess_col": "Excess",
        "tournament_nodes_col": "Nodes",
        "adv_time_horizon": "Time Horizon",
        "adv_nondet_prob": "Nondeterministic Probability",
        "adv_belief_states": "Belief States Count",
        "adv_max_steps": "Max Steps",
        "adv_game_tree_depth": "Game Tree Depth",
        "adv_success_prob": "Success Probability",
        "theory_title": "Theory Notes & PEAS Analysis",
        "theory_peas_title": "PEAS Analysis for 15-Puzzle Agent",
        "theory_detail_title": "Algorithm Theory Details",
        "theory_coming_soon": "Detailed theory for {algo} coming soon.",
        "theory_belongs_group": "Belongs to group: {group}",
        "theory_peas_peas": "PEAS Analysis",
    }
}

_MOJIBAKE_VIETNAMESE_KEY = "Ti\u00e1\u00ba\u00bfng Vi\u00e1\u00bb\u2021t"
_UNICODE_VIETNAMESE_KEY = "Ti\u1ebfng Vi\u1ec7t"
if _MOJIBAKE_VIETNAMESE_KEY in LOC and _UNICODE_VIETNAMESE_KEY not in LOC:
    LOC[_UNICODE_VIETNAMESE_KEY] = LOC[_MOJIBAKE_VIETNAMESE_KEY]

if _UNICODE_VIETNAMESE_KEY in LOC:
    LOC[_UNICODE_VIETNAMESE_KEY].update({
        "nav_play": "Ch\u01a1i \u0111\u1ed1",
        "nav_run": "Ch\u1ea1y thu\u1eadt to\u00e1n",
        "nav_trace": "Trace t\u1eebng b\u01b0\u1edbc",
        "nav_hand_trace": "Luy\u1ec7n ch\u1ea1y tay",
        "nav_compare": "So s\u00e1nh",
        "nav_theory": "L\u00fd thuy\u1ebft PEAS",
        "nav_advanced": "N\u00e2ng cao",
        "demo_workflow": "Lu\u1ed3ng demo",
        "play_title": "Tr\u00f2 ch\u01a1i 15-Puzzle | B\u00e0n c\u1edd T\u01b0\u01a1ng t\u00e1c",
        "play_reset_board": "\u0110\u1eb7t l\u1ea1i b\u00e0n ch\u01a1i",
    })


def _looks_mojibake(text: str) -> bool:
    return any(marker in text for marker in ("Ã", "Â", "Ä", "Æ", "áº", "á»", "\x90"))


def _mojibake_score(text: str) -> int:
    return sum(text.count(marker) for marker in ("Ã", "Â", "Ä", "Æ", "áº", "á»", "\x90"))


def _repair_mojibake(text: str) -> str:
    """Recover Vietnamese text that was decoded through a legacy code page."""
    if not _looks_mojibake(text):
        return text

    candidates = [text]
    for encoding in ("cp1252", "latin1"):
        try:
            candidates.append(text.encode(encoding).decode("utf-8"))
        except UnicodeError:
            continue
    try:
        legacy_bytes = bytearray()
        for character in text:
            if ord(character) <= 255:
                legacy_bytes.append(ord(character))
            else:
                legacy_bytes.extend(character.encode("cp1252"))
        candidates.append(bytes(legacy_bytes).decode("utf-8"))
    except UnicodeError:
        pass

    return min(candidates, key=_mojibake_score)


def _repair_locale_values(locale: dict[str, object]) -> None:
    for key, value in list(locale.items()):
        if isinstance(value, str):
            locale[key] = _repair_mojibake(value)


for _lang_key in (_MOJIBAKE_VIETNAMESE_KEY, _UNICODE_VIETNAMESE_KEY):
    if _lang_key in LOC:
        _repair_locale_values(LOC[_lang_key])


def resolve_language(language: str | None) -> str:
    """Return a known language key, tolerating old mojibake labels."""
    if language in LOC:
        return language
    if language and "English" in language:
        return "English"
    return _UNICODE_VIETNAMESE_KEY


def translate(language: str | None, key: str, **kwargs) -> str:
    locale = LOC.get(resolve_language(language), LOC[_UNICODE_VIETNAMESE_KEY])
    text = locale.get(key, LOC["English"].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text
