"""Localization dictionary for bilingual support (Vietnamese & English)."""

LOC = {
    "Tiếng Việt": {
        # Navigation
        "nav_play": "Chơi đố",
        "nav_run": "Chạy thuật toán",
        "nav_trace": "Trace từng bước",
        "nav_hand_trace": "Luyện chạy tay",
        "nav_compare": "So sánh",
        "nav_theory": "Lý thuyết PEAS",
        "nav_advanced": "Nâng cao (CSP/Đối kháng)",
        "demo_workflow": "Luồng demo",
        "teaching_preset": "Tình huống dạy học",
        "teaching_preset_help": "Các ca đã kiểm thử giúp nhìn rõ trade-off giữa thuật toán.",
        "load_teaching_preset": "Tải tình huống dạy học",
        "play_hero_title": "Phòng thí nghiệm giải 15-Puzzle bằng AI",
        "play_hero_desc": "Dashboard cuối kỳ để trình bày PEAS, tìm kiếm không gian trạng thái, heuristic và ranh giới giữa solver thật với phần mở rộng giáo dục.",
        "play_hero_kicker": "Dashboard cuối kỳ AI",
        "exam_step_label": "Bước",
        "exam_tab_play": "Chơi đố",
        "exam_tab_run": "Chạy thuật toán",
        "exam_tab_compare": "So sánh",
        "exam_tab_theory": "Lý thuyết PEAS",
        "exam_tab_hand": "Luyện chạy tay",
        "exam_step_play_title": "Thiết lập trạng thái",
        "exam_step_play_note": "Tải preset hoặc kiểm tra tính giải được.",
        "exam_step_run_title": "Trace một solver",
        "exam_step_run_note": "Giải thích frontier, reached và bảo đảm thuật toán.",
        "exam_step_compare_title": "Đo trade-off",
        "exam_step_compare_note": "Dùng seed, độ sâu, heuristic và caveat.",
        "exam_step_theory_title": "Bảo vệ mô hình",
        "exam_step_theory_note": "Trình bày PEAS, chứng minh, taxonomy và giới hạn.",
        "exam_step_hand_title": "Kiểm chứng bằng tay",
        "exam_step_hand_note": "Luyện thứ tự mở rộng và quy tắc phá hòa.",
        "run_hero_title": "Chạy một thuật toán kèm ngữ cảnh học thuật",
        "run_hero_desc": "Kiểm tra guarantee, giả định môi trường, trace và lý do phương pháp được chọn có phải solver tự nhiên của 15-puzzle hay không.",
        "run_hero_kicker": "Phân tích một thuật toán",
        "run_model_success_no_goal": "{algo} tạo ra kết quả hợp lệ cho mô hình demo, nhưng chưa chứng nhận đường đi chuẩn tới goal yêu cầu.",
        "run_fresh_seed": "Tạo seed ngẫu nhiên mới mỗi lần chạy",
        "run_fresh_seed_help": "Bật: mỗi lần chạy sinh trajectory stochastic mới. Tắt: dùng seed cố định để so sánh học thuật có thể tái lập.",
        "run_fixed_seed": "Seed ngẫu nhiên cố định",
        "run_deterministic_caption": "Lần chạy deterministic: cùng trạng thái, tham số, thứ tự hành động và tie-breaker có thể tạo cùng path với thuật toán tối ưu khác.",
        "run_random_seed_caption": "Seed của lần chạy ngẫu nhiên: `{seed}`. Lưu seed này để tái lập đúng lần chạy.",
        "run_recorded_trajectory": "Quỹ đạo ghi nhận (không phải lời giải)",
        "run_recorded_warning": "Các bước này là bằng chứng hành vi hợp lệ của thuật toán, nhưng trạng thái cuối chưa tới goal yêu cầu.",
        "compare_hero_title": "So sánh hành vi solver và guarantee học thuật",
        "compare_hero_desc": "Benchmark cho thấy hành vi runtime; taxonomy tách solver chuẩn của 15-puzzle khỏi contrast case và phần mở rộng AI minh họa.",
        "compare_hero_kicker": "So sánh thuật toán",
        "compare_preset": "Preset benchmark",
        "compare_load_preset_state": "Tải trạng thái preset",
        "compare_preset_caption": "Preset tải một trạng thái deterministic giải được. Bạn vẫn có thể chỉnh thuật toán, heuristic, node cap và timeout trước khi chạy.",
        "compare_select_algorithms_desc": "Chọn thuật toán để benchmark trên trạng thái bắt đầu hiện tại.",
        "compare_standard_rankings_caption": "Bảng xếp hạng chuẩn chỉ gồm solver thật và local-search contrast case. CSP, uncertainty, online và game/chance nằm trong Concept Lab vì tiêu chí thành công và giả định môi trường không so sánh trực tiếp được.",
        "compare_algorithms_from": "Thuật toán từ {group}",
        "compare_timeout": "Timeout (giây)",
        "compare_fresh_seeds": "Tạo seed stochastic mới cho mỗi benchmark",
        "compare_fresh_seeds_help": "Mỗi thuật toán stochastic nhận một seed riêng được ghi lại. Tắt tùy chọn này để dùng seed cố định cho benchmark tái lập.",
        "compare_fixed_seed": "Seed benchmark cố định",
        "compare_recorded_seeds": "Seed stochastic đã ghi nhận - {seeds}",
        "theory_hero_title": "Lý thuyết, PEAS và khung bảo vệ",
        "theory_hero_desc": "Dùng trang này để giải thích mô hình agent, guarantee thuật toán, cấu trúc dữ liệu, độ phức tạp và vì sao một số phương pháp chỉ là phần mở rộng học thuật.",
        "theory_hero_kicker": "Tài liệu học thuật",
        
        # Sidebar
        "sb_title": "Bảng Điều Khiển AI",
        "sb_start_state": "Trạng thái Bắt đầu",
        "sb_input_method": "Phương thức nhập",
        "sb_random": "Ngẫu nhiên (Scramble)",
        "sb_manual": "Nhập thủ công",
        "sb_depth": "Độ sâu xáo trộn",
        "sb_seed": "Hạt giống (Seed)",
        "sb_generate": "Tạo ngẫu nhiên",
        "sb_parse": "Phân tích đầu vào",
        "sb_reset_goal": "Đặt lại về Đích",
        "sb_solvable": "Trạng thái giải được",
        "sb_unsolvable": "Không thể giải. Tráo 2 ô để giải được.",
        "sb_sample_img": "Ảnh xếp hình mẫu",
        "sb_builtin": "Ảnh có sẵn",
        "sb_load_img": "Tải ảnh mẫu",
        "sb_show_num": "Hiển thị số trên ảnh (Helper)",
        "sb_curr_start": "Trạng thái bắt đầu hiện tại",
        
        # Tab Play
        "play_title": "Trò chơi 15-Puzzle | Bàn cờ Tương tác",
        "play_start": "Bảng bắt đầu",
        "play_goal": "Bảng đích",
        "play_custom_img": "Sử dụng ảnh tùy chọn",
        "play_upload_desc": "Tải lên một hình ảnh bất kỳ để cắt thành 15 mảnh ghép xếp hình.",
        "play_upload_label": "Chọn file ảnh",
        "play_remove_img": "Xóa ảnh tùy chọn",
        "play_manual": "Chơi bằng tay",
        "play_manual_desc": "Nhấp vào bất kỳ ô số nào kề ô trống để trượt.",
        "play_moves": "Số bước đi",
        "play_manhattan": "Khoảng cách Manhattan",
        "play_tiles_correct": "Số ô đúng vị trí",
        "play_reset_board": "Đặt lại bàn chơi",
        "play_undo": "Hoàn tác bước cuối",
        "play_challenge_title": "Chế độ thử thách học thuật",
        "play_challenge_desc": "A* với Linear Conflict admissible chứng minh khoảng cách tối ưu. Lịch sử chơi được kiểm chứng từng bước, rồi chỉ chấm điểm sau khi tới goal.",
        "play_prove_optimal": "Chứng minh số bước tối ưu",
        "play_computing_certificate": "Đang tính chứng chỉ tối ưu...",
        "slide_right": "Trượt sang phải",
        "slide_left": "Trượt sang trái",
        "slide_down": "Trượt xuống",
        "slide_up": "Trượt lên",
        "play_ai_solver": "Giải tự động bằng AI",
        "play_ai_desc": "Sử dụng thuật toán **A* Search** với Heuristic **Manhattan Distance** tìm lời giải tối ưu.",
        "play_ai_solve_btn": "Tìm lời giải bằng AI",
        "play_ai_clear_btn": "Hủy lời giải AI",
        "play_ai_running": "AI đang tính toán...",
        "play_ai_solved_msg": "Đã tìm thấy lời giải tối ưu gồm {steps} bước!",
        "play_ai_solved_info": "Lời giải tối ưu A*: **{steps} bước** | Thời gian tính: **{time:.4f}s** | Số nút mở rộng: **{expanded}** | Max Frontier: **{max_f}**",
        "play_ai_already_goal": "Bảng đã ở trạng thái đích rồi!",
        "play_ai_unsolvable": "Trạng thái hiện tại không thể giải được!",
        "play_prev_step": "Bước trước",
        "play_next_step": "Bước tiếp",
        "play_auto_run": "Chạy tự động",
        "play_stop_run": "Dừng",
        "play_curr_step": "Bước hiện tại",
        "play_action_performed": "Hành động vừa thực hiện (bước {step}/{total}): **{act}**",
        "play_auto_done": "Đã hoàn thành giải đố tự động bằng AI!",
        "play_academic_analysis": "Phân tích học thuật / Academic Analysis",
        
        # Tab Run Algorithm
        "run_title": "Chạy Thuật toán AI",
        "run_group": "Nhóm thuật toán",
        "run_algo": "Thuật toán",
        "run_heuristic": "Heuristic chọn",
        "run_params": "Tham số chạy",
        "run_max_nodes": "Giới hạn số Node",
        "run_max_depth": "Độ sâu tối đa / Độ sâu cây game",
        "run_timeout": "Thời gian chờ (giây)",
        "run_action_order": "Thứ tự hành động",
        "run_btn": "Khởi chạy thuật toán",
        "run_success": "Thuật toán {algo} đã tìm thấy lời giải!",
        "run_fail": "Thất bại: {msg}",
        "run_sol_path": "Đường đi lời giải",
        "run_trace_steps": "Các bước vết (Trace Steps)",
        "run_detail": "Chi tiết Node / Frontier / Reached",
        "run_search_tree": "Cây Tìm Kiếm (Search Tree)",
        
        # Tab Step Trace
        "trace_title": "Trace Từng Bước Thuật Toán",
        "trace_info": "Hãy chạy thuật toán để hiển thị bảng trace chi tiết.",
        "trace_export": "Xuất bảng vết dưới dạng CSV",
        
        # Tab Compare
        "compare_title": "So Sánh Hiệu Năng Thuật Toán",
        "compare_desc": "Chọn các thuật toán để đo đạc và so sánh hiệu năng trên trạng thái bắt đầu.",
        "compare_groups": "Chọn nhóm thuật toán",
        "compare_run_btn": "Bắt đầu đo hiệu năng (Benchmark)",
        "compare_running": "Đang chạy benchmark thuật toán...",
        "compare_done": "Hoàn thành: {curr}/{total}",
        "compare_prop": "Bảng so sánh thuộc tính lý thuyết",
        
        # UI Components
        "mc_status": "Trạng thái",
        "mc_solved": "Thành công (Solved)",
        "mc_failed": "Thất bại (Failed)",
        "mc_path_len": "Độ dài đường đi",
        "mc_runtime": "Thời gian chạy",
        "mc_expanded": "Số nút mở rộng",
        "mc_cost": "Chi phí (Cost)",
        "mc_max_f": "Frontier lớn nhất",
        "mc_reached_size": "Kích thước Reached",
        "mc_depth": "Độ sâu",
        "tc_no_trace": "Không có dữ liệu trace.",
        "tc_step": "Bước",
        "tc_action": "Hành động",
        "tc_frontier": "Biên giới (Frontier)",
        "tc_reached": "Đã duyệt (Reached)",
        "tc_temp": "Nhiệt độ (T)",
        "tc_prob": "Xác suất P(accept)",
        "tc_accepted": "Chấp nhận",
        "tc_yes": "Có",
        "tc_no": "Không",
        "tc_belief": "Belief State",
        "tc_type": "Loại node",
        "tc_reason": "Lý do",
        "tc_showing": "Đang hiển thị {curr} trên tổng số {total} bước",
        "det_no_detail": "Chi tiết Node/Frontier/Reached không khả dụng cho thuật toán này. Chỉ hỗ trợ BFS, DFS, UCS, IDS, Greedy, A*, IDA*.",
        "det_slider": "Chọn bước để kiểm tra chi tiết",
        "det_curr_node": "Nút hiện tại (Current Node)",
        "det_more": "... +{count} nút khác",
        "det_empty": "Trống hoặc không ghi nhận",
        "det_not_captured": "Không được ghi nhận cho thuật toán này",
        "anim_title": "Hoạt ảnh Lời giải",
        "anim_speed": "Tốc độ chạy",
        "anim_per_step": "{sec}s mỗi bước",
        "anim_goal": "Goal! Thành công",
        "anim_complete": "Hoạt ảnh đã chạy xong!",
        "anim_prev": "Bước trước",
        "anim_next": "Bước sau",
        "anim_reset": "Đặt lại",
        "eval_title": "Đánh Giá Học Thuật (Academic Evaluation)",
        "eval_prop": "Thuộc tính (Property)",
        "eval_val": "Thông tin học thuật (Academic Value)",
        "eval_complete": "Tính đầy đủ (Completeness)",
        "eval_optimal": "Tính tối ưu (Optimality)",
        "eval_time": "Độ phức tạp thời gian (Time Complexity)",
        "eval_space": "Độ phức tạp không gian (Space Complexity)",
        "eval_suit": "Độ phù hợp 15-Puzzle (Suitability)",
        "eval_pros": "Ưu điểm (Pros)",
        "eval_cons": "Nhược điểm (Cons)",
        "eval_tips": "Lưu ý ôn thi (Exam Tips)",
        "eval_not_found": "Không tìm thấy dữ liệu đánh giá cho thuật toán này.",
        
        # Directions
        "dir_L": "Trái (trượt ô số sang phải)",
        "dir_R": "Phải (trượt ô số sang trái)",
        "dir_U": "Lên (trượt ô số xuống dưới)",
        "dir_D": "Xuống (trượt ô số lên trên)",
        "dir_Start": "Bắt đầu",
        "dir_Goal": "Đích",
        
        # Hand-Tracing Tab
        "ht_title": "Luyện Tập Chạy Tay (Hand-Tracing Practice)",
        "ht_desc": "Chế độ học thuật giúp bạn tập chạy tay thuật toán trên giấy và đối chiếu kết quả từng bước (Frontier, Reached, Cây tìm kiếm) để chuẩn bị cho kỳ thi lý thuyết.",
        "ht_setup": "Thiết lập Thử thách mới",
        "ht_scramble": "Độ sâu tối ưu (Scramble Depth)",
        "ht_scramble_help": "Nên chọn 1-3 bước để chạy tay trên giấy khả thi (dưới 10 bước).",
        "ht_order": "Thứ tự hành động sinh con (Action Order)",
        "ht_order_help": "Thứ tự di chuyển ô trống. Rất quan trọng để khớp đáp án.",
        "ht_btn_generate": "Tạo Thử Thách Mới",
        "ht_btn_cancel": "Hủy thử thách",
        "ht_cur_state": "Trạng thái bàn cờ hiện tại",
        "ht_state_start": "Bắt đầu (Start)",
        "ht_state_curr": "Đang xét (Current)",
        "ht_state_goal": "Đích (Goal)",
        "ht_curr_step": "Bước hiện tại: {step}",
        "ht_success_msg": "Chúc mừng! Bạn đã hoàn thành xuất sắc thử thách chạy tay!",
        "ht_table_title": "Bảng Trace đáp án hoàn chỉnh của bạn:",
        "ht_tree_title": "Cây tìm kiếm đã vẽ:",
        "ht_btn_new": "Luyện tập thử thách mới",
        "ht_decision": "Quyết định Chạy Tay của bạn",
        "ht_decision_desc": "Dựa trên thuật toán hiện tại, **nút nào trong Frontier sẽ được mở rộng tiếp theo**?",
        "ht_choice": "Lựa chọn {num}",
        "ht_choice_btn": "Mở rộng Lựa chọn {num}",
        "ht_expanded_to": "Hành động dẫn tới: `{act}`",
        "ht_expand_success": "Chính xác! Bạn đã mở rộng đúng node {num}.",
        "ht_expand_error": "Sai rồi! Bạn đã chọn mở rộng nút `{chosen}` ({chosen_val}). Nhưng theo thuật toán {algo} và quy tắc giải quyết cân bằng {tb}, nút đúng phải mở rộng là `{correct}` ({correct_val}). Hãy phân tích lại Frontier và chọn lại.",
        "ht_frontier_title": "Frontier (Biên giới) - {count} nút:",
        "ht_reached_title": "Reached (Đã duyệt) - {count} trạng thái:",
        "ht_history_title": "Bảng Trace của bạn (Lịch sử các bước đúng)",
        
        # Extra translations added for complete localization
        "sb_manual_desc": "Nhập 16 số (0=ô trống, cách nhau bằng dấu cách)",
        "sb_parse_success": "Đã phân tích trạng thái thành công!",
        "sb_parse_error": "Đầu vào không hợp lệ: {error}",
        "play_solvable_label": "Giải được?",
        "play_img_loaded": "Ảnh đã tải! Đã tạo ra {count} mảnh ghép.",
        "play_img_failed": "Tải ảnh thất bại. Hãy chắc chắn đó là file ảnh hợp lệ.",
        "play_target_preview": "Ảnh Gốc Xem Trước",
        "play_preview_fail": "Không thể tạo ảnh xem trước.",
        "play_preview_error": "Lỗi tải xem trước: {error}",
        "play_preview_none": "Không có ảnh xem trước.",
        "play_solved_success": "Chúc mừng! Bạn đã giải được câu đố sau {moves} bước!",
        "play_ai_solve_btn_full": "Tìm lời giải bằng AI (A* Manhattan)",
        "play_ai_error": "Lỗi tìm kiếm lời giải: {error}",
        "play_curr_step_label": "Bước hiện tại: {step}/{total}",
        "run_tie_breaker": "Quy tắc phá vỡ cân bằng (Tie-breaking)",
        "run_tie_breaker_help": "Quy tắc chọn node khi chi phí f(n) hoặc g(n)/h(n) bằng nhau. Cực kỳ hữu ích để sinh viên đối chiếu khi chạy tay.",
        "run_max_iter": "Số lần lặp tối đa (Max Iterations)",
        "run_seed": "Hạt giống ngẫu nhiên (Random Seed)",
        "run_max_restarts": "Số lần thử lại tối đa (Max Restarts)",
        "run_beam_width": "Độ rộng chùm tia (Beam Width)",
        "run_init_temp": "Nhiệt độ ban đầu (Initial Temp)",
        "run_cooling_rate": "Tốc độ làm mát (Cooling Rate)",
        "run_min_temp": "Nhiệt độ tối thiểu (Min Temp)",
        "run_success_prob": "Xác suất thành công (Success Prob)",
        "run_error_unsolvable": "Trạng thái bắt đầu không giải được. Vui lòng tạo trạng thái giải được.",
        "run_error_not_found": "Không tìm thấy thuật toán {algo}.",
        "run_error_func_not_found": "Không tìm thấy hàm giải {func}.",
        "run_spinner_running": "Đang chạy {algo}...",
        "run_error_exception": "Lỗi khi chạy {algo}: {error}",
        "compare_heuristic": "Heuristic dùng để so sánh",
        "compare_benchmark_title": "Đo Hiệu Năng Thuật Toán",
        "compare_analysis": "Phân tích so sánh hiệu năng",
        "compare_fastest": "Nhanh nhất: **{algo}** ({time:.4f}s)",
        "compare_shortest": "Đường đi ngắn nhất: **{algo}** ({steps} bước)",
        "compare_most_memory": "Tốn bộ nhớ nhất: **{algo}** ({nodes} nodes)",
        "compare_no_data": "Hãy chạy benchmark để hiển thị bảng so sánh.",
        "compare_optimal_col": "Tối ưu?",
        "compare_complete_col": "Đầy đủ?",
        "compare_group_col": "Nhóm",
        "adv_mode": "Chế độ Nâng cao",
        "adv_time_horizon": "Giới hạn thời gian (Time Horizon)",
        "adv_nondet_prob": "Xác suất không xác định",
        "adv_belief_states": "Số lượng Belief States",
        "adv_max_steps": "Số bước tối đa",
        "adv_game_tree_depth": "Độ sâu cây trò chơi",
        "adv_success_prob": "Xác suất dịch chuyển thành công",
        "theory_title": "Tài Liệu Lý Thuyết & Phân Tích PEAS",
        "theory_peas_title": "Phân tích PEAS cho Đại lý giải 15-Puzzle",
        "theory_detail_title": "Chi tiết lý thuyết thuật toán",
        "theory_coming_soon": "Chi tiết lý thuyết cho {algo} sẽ sớm được cập nhật.",
        "theory_belongs_group": "Thuộc nhóm thuật toán: {group}",
        "theory_peas_peas": "Phân tích PEAS"
    },
    "English": {
        # Navigation
        "nav_play": "Play Puzzle",
        "nav_run": "Run Algorithm",
        "nav_trace": "Step Trace",
        "nav_hand_trace": "Hand-Tracing Practice",
        "nav_compare": "Compare",
        "nav_theory": "PEAS Theory",
        "nav_advanced": "Advanced Mode",
        "demo_workflow": "Demo Workflow",
        "teaching_preset": "Teaching Preset",
        "teaching_preset_help": "Audited cases that make algorithm tradeoffs visible.",
        "load_teaching_preset": "Load Teaching Preset",
        "play_hero_title": "15-Puzzle AI Solver Lab",
        "play_hero_desc": "A final-exam dashboard for demonstrating PEAS, state-space search, heuristics, and the boundary between real solvers and educational extensions.",
        "play_hero_kicker": "AI final exam dashboard",
        "exam_step_label": "Step",
        "exam_tab_play": "Play",
        "exam_tab_run": "Run",
        "exam_tab_compare": "Compare",
        "exam_tab_theory": "Theory/PEAS",
        "exam_tab_hand": "Hand-Tracing",
        "exam_step_play_title": "Set state",
        "exam_step_play_note": "Load a preset or inspect solvability.",
        "exam_step_run_title": "Trace one solver",
        "exam_step_run_note": "Explain frontier, reached, and guarantees.",
        "exam_step_compare_title": "Measure tradeoffs",
        "exam_step_compare_note": "Use seed, depth, heuristic, and caveat.",
        "exam_step_theory_title": "Defend model",
        "exam_step_theory_note": "Show PEAS, proofs, taxonomy, and limits.",
        "exam_step_hand_title": "Verify by hand",
        "exam_step_hand_note": "Practice expansion order and tie-breaking.",
        "run_hero_title": "Run one algorithm with academic context",
        "run_hero_desc": "Inspect guarantees, environment assumptions, trace data, and why the selected method is or is not a natural 15-puzzle solver.",
        "run_hero_kicker": "Single algorithm analysis",
        "run_model_success_no_goal": "{algo} produced a successful model result, but it did not certify a standard path to the requested goal.",
        "run_fresh_seed": "Fresh random seed each run",
        "run_fresh_seed_help": "Enabled: each run samples a new stochastic trajectory. Disabled: reuse a fixed seed for reproducible academic comparison.",
        "run_fixed_seed": "Fixed Random Seed",
        "run_deterministic_caption": "Deterministic run: identical state, parameters, action order, and tie-breaker may legitimately produce the same path as another optimal algorithm.",
        "run_random_seed_caption": "Randomized run seed: `{seed}`. Save this seed to reproduce this exact run.",
        "run_recorded_trajectory": "Recorded Trajectory (not a solution)",
        "run_recorded_warning": "These moves are legal evidence of the algorithm's behavior, but the final state did not reach the requested goal.",
        "compare_hero_title": "Compare solver behavior and academic guarantees",
        "compare_hero_desc": "Benchmark results show runtime behavior; the taxonomy table separates standard 15-puzzle solvers from contrast cases and illustrative AI extensions.",
        "compare_hero_kicker": "Algorithm comparison",
        "compare_preset": "Benchmark preset",
        "compare_load_preset_state": "Load preset state",
        "compare_preset_caption": "Preset loads a deterministic solvable state. You can still adjust algorithms, heuristic, node cap, and timeout before running.",
        "compare_select_algorithms_desc": "Select algorithms to benchmark against the current start state.",
        "compare_standard_rankings_caption": "Standard rankings include real solvers and local-search contrast cases only. CSP, uncertainty, online, and game/chance models remain in Concept Lab because their success criteria and environment assumptions are not directly comparable.",
        "compare_algorithms_from": "Algorithms from {group}",
        "compare_timeout": "Timeout (s)",
        "compare_fresh_seeds": "Fresh stochastic seeds each benchmark",
        "compare_fresh_seeds_help": "Each stochastic algorithm receives a distinct recorded seed. Disable this to reuse a fixed seed for a reproducible benchmark.",
        "compare_fixed_seed": "Fixed benchmark seed",
        "compare_recorded_seeds": "Recorded stochastic seeds - {seeds}",
        "theory_hero_title": "Theory notes, PEAS, and exam framing",
        "theory_hero_desc": "Use this page to explain the agent model, algorithm guarantees, data structures, complexity, and why some methods are only academic extensions.",
        "theory_hero_kicker": "Academic reference",
        
        # Sidebar
        "sb_title": "AI Control Panel",
        "sb_start_state": "Start State",
        "sb_input_method": "Input method",
        "sb_random": "Random (Scramble)",
        "sb_manual": "Manual Input",
        "sb_depth": "Scramble Depth",
        "sb_seed": "Seed",
        "sb_generate": "Generate Random",
        "sb_parse": "Parse Input",
        "sb_reset_goal": "Reset to Goal",
        "sb_solvable": "Solvable state",
        "sb_unsolvable": "Unsolvable. Swap 2 tiles to fix.",
        "sb_sample_img": "Sample Image Mode",
        "sb_builtin": "Built-in images",
        "sb_load_img": "Load Sample Image",
        "sb_show_num": "Show numbers on image (Helper)",
        "sb_curr_start": "Current Start State",
        
        # Tab Play
        "play_title": "15-Puzzle | Interactive Board",
        "play_start": "Start State",
        "play_goal": "Goal State",
        "play_custom_img": "Custom Image Upload",
        "play_upload_desc": "Upload any image to split it into 15 puzzle tiles.",
        "play_upload_label": "Upload puzzle image",
        "play_remove_img": "Remove Custom Image",
        "play_manual": "Manual Play",
        "play_manual_desc": "Click any tile adjacent to the blank space to slide it.",
        "play_moves": "Moves Played",
        "play_manhattan": "Manhattan Distance",
        "play_tiles_correct": "Tiles in Goal Position",
        "play_reset_board": "Reset Board",
        "play_undo": "Undo Last Move",
        "play_challenge_title": "Academic Challenge Mode",
        "play_challenge_desc": "A* with admissible Linear Conflict proves the optimal distance. Your recorded play history is certified step-by-step, then scored only after it reaches the goal.",
        "play_prove_optimal": "Prove Optimal Move Count",
        "play_computing_certificate": "Computing an optimal certificate...",
        "slide_right": "Slide right",
        "slide_left": "Slide left",
        "slide_down": "Slide down",
        "slide_up": "Slide up",
        "play_ai_solver": "AI Auto-Solver",
        "play_ai_desc": "Uses **A* Search** with **Manhattan Distance** heuristic to find the optimal path.",
        "play_ai_solve_btn": "Find Solution via AI",
        "play_ai_clear_btn": "Discard AI Solution",
        "play_ai_running": "AI is computing...",
        "play_ai_solved_msg": "Found optimal solution in {steps} steps!",
        "play_ai_solved_info": "A* Optimal Solution: **{steps} steps** | Runtime: **{time:.4f}s** | Nodes Expanded: **{expanded}** | Max Frontier: **{max_f}**",
        "play_ai_already_goal": "Board is already at goal state!",
        "play_ai_unsolvable": "Current board state is unsolvable!",
        "play_prev_step": "Prev Step",
        "play_next_step": "Next Step",
        "play_auto_run": "Auto Play",
        "play_stop_run": "Pause",
        "play_curr_step": "Current Step",
        "play_action_performed": "Action performed (step {step}/{total}): **{act}**",
        "play_auto_done": "AI Auto-solving complete!",
        "play_academic_analysis": "Academic Analysis & State-Space",
        
        # Tab Run Algorithm
        "run_title": "Run Search Algorithm",
        "run_group": "Algorithm Group",
        "run_algo": "Algorithm",
        "run_heuristic": "Heuristic Function",
        "run_params": "Search Parameters",
        "run_max_nodes": "Max Nodes Limit",
        "run_max_depth": "Max Depth / Game Tree Depth",
        "run_timeout": "Timeout (seconds)",
        "run_action_order": "Action Order (Blank Move)",
        "run_btn": "Run Search Algorithm",
        "run_success": "{algo} found a solution!",
        "run_fail": "Failed: {msg}",
        "run_sol_path": "Solution Path",
        "run_trace_steps": "Trace Steps",
        "run_detail": "Node / Frontier / Reached Detail",
        "run_search_tree": "Search Tree Visualization",
        
        # Tab Step Trace
        "trace_title": "Step-by-Step Search Trace",
        "trace_info": "Run an algorithm first to see its step-by-step trace.",
        "trace_export": "Export Trace as CSV",
        
        # Tab Compare
        "compare_title": "Compare Algorithm Performance",
        "compare_desc": "Select algorithms to benchmark and compare on the current start state.",
        "compare_groups": "Algorithm Groups",
        "compare_run_btn": "Run Performance Benchmark",
        "compare_running": "Running algorithm benchmark...",
        "compare_done": "Done: {curr}/{total}",
        "compare_prop": "Theoretical Properties Comparison Table",
        
        # UI Components
        "mc_status": "Status",
        "mc_solved": "Solved",
        "mc_failed": "Failed",
        "mc_path_len": "Path Length",
        "mc_runtime": "Runtime",
        "mc_expanded": "Nodes Expanded",
        "mc_cost": "Cost",
        "mc_max_f": "Max Frontier",
        "mc_reached_size": "Reached Size",
        "mc_depth": "Depth",
        "tc_no_trace": "No trace data available.",
        "tc_step": "Step",
        "tc_action": "Action",
        "tc_frontier": "Frontier Size",
        "tc_reached": "Reached Size",
        "tc_temp": "Temperature (T)",
        "tc_prob": "P(accept)",
        "tc_accepted": "Accepted",
        "tc_yes": "Yes",
        "tc_no": "No",
        "tc_belief": "Belief State",
        "tc_type": "Node Type",
        "tc_reason": "Reason",
        "tc_showing": "Showing {curr} of {total} steps",
        "det_no_detail": "Node/Frontier/Reached detail not available for this algorithm. Only available for BFS, DFS, UCS, IDS, Greedy, A*, IDA*.",
        "det_slider": "Select step to inspect",
        "det_curr_node": "Current Node",
        "det_more": "... +{count} more nodes",
        "det_empty": "Empty or not captured",
        "det_not_captured": "Not captured for this algorithm",
        "anim_title": "Solution Animation",
        "anim_speed": "Playback Speed",
        "anim_per_step": "{sec}s per step",
        "anim_goal": "Goal reached!",
        "anim_complete": "Solution animation complete!",
        "anim_prev": "Prev",
        "anim_next": "Next",
        "anim_reset": "Reset",
        "eval_title": "Academic Evaluation",
        "eval_prop": "Property",
        "eval_val": "Academic Value",
        "eval_complete": "Completeness",
        "eval_optimal": "Optimality",
        "eval_time": "Time Complexity",
        "eval_space": "Space Complexity",
        "eval_suit": "15-Puzzle Suitability",
        "eval_pros": "Pros",
        "eval_cons": "Cons",
        "eval_tips": "Exam Tips",
        "eval_not_found": "No academic evaluation data found for this algorithm.",
        
        # Directions
        "dir_L": "Left (slides tile right)",
        "dir_R": "Right (slides tile left)",
        "dir_U": "Up (slides tile down)",
        "dir_D": "Down (slides tile up)",
        "dir_Start": "Start",
        "dir_Goal": "Goal",
        
        # Hand-Tracing Tab
        "ht_title": "Hand-Tracing Practice Mode",
        "ht_desc": "An academic mode to practice trace steps on paper and verify your answers (Frontier, Reached, Search Tree) for exam preparation.",
        "ht_setup": "Setup New Challenge",
        "ht_scramble": "Optimal Path Length (Scramble Depth)",
        "ht_scramble_help": "Recommend 1-3 steps to keep manual tracing realistic on paper (under 10 steps total).",
        "ht_order": "Blank Move Order (Action Order)",
        "ht_order_help": "Order of generating children. Critical to match answers.",
        "ht_btn_generate": "Generate New Challenge",
        "ht_btn_cancel": "Cancel Challenge",
        "ht_cur_state": "Current Board State",
        "ht_state_start": "Start State",
        "ht_state_curr": "Current State",
        "ht_state_goal": "Goal State",
        "ht_curr_step": "Current Step: {step}",
        "ht_success_msg": "Congratulations! You have successfully solved the hand-tracing challenge!",
        "ht_table_title": "Your Completed Tracing Table:",
        "ht_tree_title": "Search Tree Generated:",
        "ht_btn_new": "Start New Practice",
        "ht_decision": "Your Hand-Tracing Choice",
        "ht_decision_desc": "Based on the search strategy, **which node in the Frontier will be expanded next**?",
        "ht_choice": "Option {num}",
        "ht_choice_btn": "Expand Option {num}",
        "ht_expanded_to": "Action leading to: `{act}`",
        "ht_expand_success": "Correct choice! You expanded node {num}.",
        "ht_expand_error": "Incorrect! You selected node `{chosen}` ({chosen_val}). But according to **{algo}** and tie-breaking rule **{tb}**, the correct node to expand is `{correct}` ({correct_val}). Analyze the Frontier and try again.",
        "ht_frontier_title": "Frontier - {count} nodes:",
        "ht_reached_title": "Reached - {count} states:",
        "ht_history_title": "Your Tracing Table (Correct Steps History)",
        
        # Extra translations added for complete localization
        "sb_manual_desc": "Enter 16 numbers (0=blank, space-separated)",
        "sb_parse_success": "State parsed successfully!",
        "sb_parse_error": "Invalid input: {error}",
        "play_solvable_label": "Is Solvable?",
        "play_img_loaded": "Image loaded! {count} tile pieces created.",
        "play_img_failed": "Failed to load image. Make sure it's a valid image file.",
        "play_target_preview": "Target Preview",
        "play_preview_fail": "Preview could not be generated.",
        "play_preview_error": "Error loading preview: {error}",
        "play_preview_none": "No preview available.",
        "play_solved_success": "Congratulations! You solved the puzzle in {moves} moves!",
        "play_ai_solve_btn_full": "Find Solution via AI (A* Manhattan)",
        "play_ai_error": "Error finding solution: {error}",
        "play_curr_step_label": "Current Step: {step}/{total}",
        "run_tie_breaker": "Tie-breaking Rule",
        "run_tie_breaker_help": "Rule to select a node when evaluations are equal. Extremely useful for students to compare with manual tracing.",
        "run_max_iter": "Max Iterations",
        "run_seed": "Random Seed",
        "run_max_restarts": "Max Restarts",
        "run_beam_width": "Beam Width",
        "run_init_temp": "Initial Temp",
        "run_cooling_rate": "Cooling Rate",
        "run_min_temp": "Min Temp",
        "run_success_prob": "Success Probability",
        "run_error_unsolvable": "Current state is NOT solvable. Please generate a solvable state.",
        "run_error_not_found": "Algorithm {algo} not found.",
        "run_error_func_not_found": "Solver function {func} not found.",
        "run_spinner_running": "Running {algo}...",
        "run_error_exception": "Error running {algo}: {error}",
        "compare_heuristic": "Heuristic for comparison",
        "compare_benchmark_title": "Compare Algorithm Performance",
        "compare_analysis": "Performance Comparison Analysis",
        "compare_fastest": "Fastest: **{algo}** ({time:.4f}s)",
        "compare_shortest": "Shortest path: **{algo}** ({steps} steps)",
        "compare_most_memory": "Most memory: **{algo}** ({nodes} nodes)",
        "compare_no_data": "Run benchmarks to see the comparison table.",
        "compare_optimal_col": "Optimal?",
        "compare_complete_col": "Complete?",
        "compare_group_col": "Group",
        "adv_mode": "Advanced Mode",
        "adv_time_horizon": "Time Horizon",
        "adv_nondet_prob": "Nondeterministic Probability",
        "adv_belief_states": "Belief States Count",
        "adv_max_steps": "Max Steps",
        "adv_game_tree_depth": "Game Tree Depth",
        "adv_success_prob": "Success Probability",
        "theory_title": "Theory Notes & PEAS Analysis",
        "theory_peas_title": "PEAS Analysis for 15-Puzzle Agent",
        "theory_detail_title": "Algorithm Theory Details",
        "theory_coming_soon": "Detailed theory for {algo} coming soon.",
        "theory_belongs_group": "Belongs to group: {group}",
        "theory_peas_peas": "PEAS Analysis"
    }
}
